import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

const artists = [
  // === BATCH 1: SEU Worship, Vineyard Worship, McClures, Hastings, REVERE, Torwalts, Mitch Wong ===
  {
    name: "SEU Worship",
    type: "band",
    founded_year: 2010,
    location: "Lakeland, Florida",
    church_label: "Southeastern University / Essential Worship",
    bio: "SEU Worship is a contemporary worship music collective from Southeastern University in Lakeland, Florida. The group is composed of students and alumni who write and perform songs primarily for the university's weekly chapel services, crafting prophetic, theologically sound lyrics that resonate especially with young adults. Signed to Essential Worship and Provident Label Group (Sony Music), they released their first live album No Other Name in 2013 and have since released over 11 albums including projects in Spanish. Notable alumni include Grammy-winning artists Tiffany Hudson (Elevation Worship) and Sam Simon (Maverick City Music).",
    style: "Contemporary worship, pop-influenced praise with elements of EDM, indie, and modern production",
    awards: null,
    url_website: "https://seuworship.com/",
    url_wiki: "https://en.wikipedia.org/wiki/SEU_Worship",
    url_youtube: "https://www.youtube.com/@SEUWorship",
    url_apple_music: "https://music.apple.com/us/artist/seu-worship/596164472",
    url_spotify: "https://open.spotify.com/artist/7M7UXUwtz3Wb25PVS8dwHs",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Vineyard Worship",
    type: "band",
    founded_year: 1985,
    location: "Anaheim, California",
    church_label: "Vineyard Churches / Vineyard Music",
    bio: "Vineyard Worship is the worship music ministry and record label of the Association of Vineyard Churches, founded by John Wimber in 1985 as Mercy Records before becoming Vineyard Music. Born from the charismatic Vineyard movement, it became one of the most influential forces in contemporary worship music from the mid-1980s through the early 2000s. Their catalog spans over four decades and includes iconic songs like 'Come Now Is the Time to Worship' and 'Hungry (Falling on My Knees).' Vineyard Worship features a rotating collective of worship leaders and songwriters including Brian Doerksen, Brenton Brown, and Andy Park.",
    style: "Intimate contemporary worship, folk-influenced praise, acoustic-driven with a legacy of simple, heartfelt congregational songs",
    awards: null,
    url_website: "https://www.vineyardworship.com/",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@VineyardWorshipOfficial",
    url_apple_music: "https://music.apple.com/us/artist/vineyard-worship/120979164",
    url_spotify: "https://open.spotify.com/artist/7cvnCTBvMm6OvTutfCpxjL",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Paul McClure",
    type: "solo",
    founded_year: 2011,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Paul McClure is a worship leader and songwriter at Bethel Church and with Bethel Music. Originally from High Point, North Carolina, he began leading worship as a teenager at his local church before relocating to Redding, California in 2011 with his wife Hannah after attending a Bethel Music conference. He made his Bethel Music debut with 'Jesus, We Love You' from the chart-topping 2015 live album We Will Not Be Shaken, and his 2019 live performance of 'Way Maker' at Bethel Church has garnered over 32 million views. Together with Hannah, he released their debut album The Way Home in 2019.",
    style: "Contemporary worship with country, folk, and indie rock influences",
    awards: "2025 GMA Dove Award nomination (Christmas/Special Event Album of the Year)",
    url_website: "https://paulandhannahmcclure.com/",
    url_wiki: "https://en.wikipedia.org/wiki/The_McClures",
    url_youtube: "https://www.youtube.com/@TheMcClures",
    url_apple_music: "https://music.apple.com/us/artist/paul-mcclure/74247275",
    url_spotify: "https://open.spotify.com/artist/7Dl8usoHibuYnDVT5PRVnz",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Hannah McClure",
    type: "solo",
    founded_year: 2011,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Hannah McClure is a worship leader and songwriter at Bethel Church and with Bethel Music. She grew up in High Point, North Carolina, where she began leading worship as a teenager alongside her husband Paul before the couple relocated to Redding, California in 2011. Hannah has contributed to numerous Bethel Music projects and is best known for co-writing the beloved worship anthem 'Jesus We Love You.' Together with Paul, she released The Way Home in 2019 and the live album After Your Heart (Live) in 2025.",
    style: "Contemporary worship with intimate, heartfelt vocals and folk-influenced arrangements",
    awards: "2025 GMA Dove Award nomination (Christmas/Special Event Album of the Year)",
    url_website: "https://paulandhannahmcclure.com/",
    url_wiki: "https://en.wikipedia.org/wiki/The_McClures",
    url_youtube: "https://www.youtube.com/@TheMcClures",
    url_apple_music: "https://music.apple.com/us/artist/hannah-mcclure/416346904",
    url_spotify: "https://open.spotify.com/artist/13rWahXxJX1NS64MDS24Ya",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Benjamin William Hastings",
    type: "solo",
    founded_year: 2017,
    location: "Nashville, Tennessee",
    church_label: "Capitol CMG",
    bio: "Benjamin William Hastings (born November 15, 1991) is a Northern Irish Christian music artist known for his work with Hillsong Worship and Hillsong United. Growing up in Belfast, he moved to Sydney, Australia, where he became part of the Hillsong worship team around 2013. He is the writer of numerous globally recognized worship songs including the RIAA platinum-certified 'So Will I (100 Billion X),' Cory Asbury's No. 1 hit 'The Father's House,' Brandon Lake's 'Gratitude,' and Hillsong Worship's 'O Praise the Name (Anastasis).' In 2022, he launched his solo career and relocated to Nashville.",
    style: "Contemporary worship, indie folk-pop, singer-songwriter with raw vulnerability and poetic lyricism",
    awards: "RIAA Platinum certification for 'So Will I (100 Billion X)'; multiple Billboard Hot Christian Songs chart entries",
    url_website: "https://www.benjaminwilliamhastings.com/",
    url_wiki: "https://en.wikipedia.org/wiki/Benjamin_William_Hastings",
    url_youtube: "https://www.youtube.com/@BenjaminWilliamHastings",
    url_apple_music: "https://music.apple.com/us/artist/benjamin-william-hastings/976350278",
    url_spotify: "https://open.spotify.com/artist/6CK4CBL0n07VdVZmfh40nm",
    photo_url: null,
    status: "draft",
  },
  {
    name: "REVERE",
    type: "band",
    founded_year: 2020,
    location: "Cleveland, Tennessee",
    church_label: "Integrity Music",
    bio: "REVERE is a multi-national, multi-ethnic, multi-generational worship collective founded in 2020 by Integrity Music. The project was initially recorded at Lee University in Cleveland, Tennessee, just two weeks before COVID-19 shut down the world, featuring the Lee University Singers as the resident choir. REVERE brings together a diverse roster of worship leaders including Leeland Mooring, Laura Hackett Park, Mitch and Steph Wong, Phil Thompson, and David and Nicole Binion. The collective's mission is to steer the Church toward a reverential culture focused on the person of Jesus.",
    style: "Reverential worship, multicultural and multilingual contemporary praise with a focus on intimacy and intensity",
    awards: null,
    url_website: "https://www.revere.live/",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@REVERElive",
    url_apple_music: "https://music.apple.com/us/artist/revere/1514586496",
    url_spotify: "https://open.spotify.com/artist/6zkdTZfnE7saiqjwivXOTm",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Bryan & Katie Torwalt",
    type: "band",
    founded_year: 2006,
    location: "Sacramento, California",
    church_label: "Jesus Culture Music / Capitol CMG",
    bio: "Bryan & Katie Torwalt are an American Christian music husband-and-wife duo from Sacramento, California. Bryan (born June 14, 1985, in Canada) and Katie (born August 14, 1988, in Sonoma County, California) met at a Bethel Ministry event in Redding in 2006, married in 2009, and have been part of Jesus Culture Music since 2010. Their debut album Here on Earth (2011) featured the Grammy-winning song 'Holy Spirit,' which became a global worship staple. Their second album Kingdom Come (2013) reached No. 3 on Billboard's Christian Albums chart and No. 43 on the Billboard 200.",
    style: "Contemporary Christian worship, Christian rock, alternative worship with powerful anthemic praise",
    awards: "Grammy Award (Best Contemporary Christian Music Performance/Song via Francesca Battistelli's cover of 'Holy Spirit', 2016)",
    url_website: "https://www.bryanandkatietorwalt.com/",
    url_wiki: "https://en.wikipedia.org/wiki/Bryan_%26_Katie_Torwalt",
    url_youtube: "https://www.youtube.com/@torwaltmusic",
    url_apple_music: "https://music.apple.com/us/artist/bryan-katie-torwalt/447595365",
    url_spotify: "https://open.spotify.com/artist/7bvAtcPT3evvSeHDyu2zBC",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Mitch Wong",
    type: "solo",
    founded_year: null,
    location: "Nashville, Tennessee",
    church_label: "Integrity Music",
    bio: "Mitch Wong is an Australian-born Grammy award-winning songwriter, musician, and worship leader originally from Melbourne who now resides in Nashville, Tennessee with his wife Steph. He has been one of the most successful staff writers in the history of Integrity Music, collaborating with artists including Chris Tomlin, CeCe Winans, Kari Jobe, Matt Redman, Brooke Ligertwood, Kim Walker-Smith, and Cody Carnes. Wong won a Grammy Award in 2022 as co-writer of CeCe Winans' 'Believe For It.' He is also a featured artist and worship leader with the REVERE collective.",
    style: "Contemporary worship, energetic praise to intimate psalms, globally-minded songwriting for the Church",
    awards: "Grammy Award (2022, co-writer of CeCe Winans' 'Believe For It')",
    url_website: "https://www.mitchwongmusic.com/",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@MitchWongMusic",
    url_apple_music: "https://music.apple.com/us/artist/mitch-wong/923097327",
    url_spotify: "https://open.spotify.com/artist/0NmuD3IXcEGYAEX5hZxu39",
    photo_url: null,
    status: "draft",
  },

  // === BATCH 2: Kristian Stanfill, William McDowell, Jeremy Camp, NONAH, Meredith Andrews, Tiffany Hudson, We Are Messengers, Jesus Image ===
  {
    name: "Kristian Stanfill",
    type: "solo",
    founded_year: 2005,
    location: "Atlanta, Georgia",
    church_label: "Passion City Church / sixstepsrecords / Capitol CMG",
    bio: "Kristian Stanfill is an American contemporary Christian music singer, songwriter, and worship leader born on April 9, 1983, in Marietta, Georgia. He has been an anchor worship leader with the Passion Movement since 2005 and currently serves as worship pastor at Passion City Church in Atlanta. His catalog includes hit songs like 'Glorious Day,' 'God, You're So Good,' and the RIAA Gold-certified 'One Thing Remains,' amassing over 100 million streams. His 2022 album Make It Out Alive addressed personal struggles with mental health and sobriety.",
    style: "Contemporary worship, pop worship, anthemic congregational praise",
    awards: "GMA Dove Award nomination for Best New Artist (2011); RIAA Gold certification for 'One Thing Remains'",
    url_website: "https://www.kristianstanfill.com/",
    url_wiki: "https://en.wikipedia.org/wiki/Kristian_Stanfill",
    url_youtube: "https://www.youtube.com/@kristianstanfill",
    url_apple_music: "https://music.apple.com/us/artist/kristian-stanfill/137280413",
    url_spotify: "https://open.spotify.com/artist/61fqRzZ9aHyPeTdUIqEEFx",
    photo_url: null,
    status: "draft",
  },
  {
    name: "William McDowell",
    type: "solo",
    founded_year: 2009,
    location: "Orlando, Florida",
    church_label: "Deeper Fellowship Church / Integrity Music",
    bio: "William David McDowell is an American gospel musician, pastor, and worship leader born on August 31, 1976, in Cincinnati, Ohio. He began playing piano at age five and was leading his own worship sessions by age eighteen. He gained widespread recognition with his 2009 debut As We Worship Live, which reached number three on Billboard's Gospel Albums chart. His album Withholding Nothing earned a Grammy nomination for Best Gospel Album and a Stellar Award. He serves as lead pastor of Deeper Fellowship Church in Orlando, Florida.",
    style: "Gospel worship, contemporary praise and worship, charismatic worship",
    awards: "Grammy nomination for Best Gospel Album (Withholding Nothing); GMA Dove Award (Sounds of Revolution); multiple Stellar Awards",
    url_website: "https://www.williammcdowellmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/William_McDowell_(musician)",
    url_youtube: "https://www.youtube.com/@WilliamMcDowellMusic",
    url_apple_music: "https://music.apple.com/us/artist/william-mcdowell/301657422",
    url_spotify: "https://open.spotify.com/artist/6PTGRlwNbg36Mu4boWlixN",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jeremy Camp",
    type: "solo",
    founded_year: 2002,
    location: "Lafayette, Indiana",
    church_label: "Capitol CMG / BEC Recordings",
    bio: "Jeremy Thomas Camp is an American contemporary Christian music singer-songwriter born on January 12, 1978, in Lafayette, Indiana. He studied theology at Calvary Chapel Bible College before launching his recording career with his 2002 debut album Stay. Over his career he has released thirteen-plus albums, sold over seven million copies, accumulated over four billion streams, and earned 46 number-one singles across all Christian radio formats. His life story was adapted into the 2020 biographical film I Still Believe. He has won five GMA Dove Awards and received a Grammy nomination.",
    style: "Contemporary Christian, Christian rock, pop rock worship, acoustic ballads",
    awards: "5 GMA Dove Awards; Grammy nomination (2010); 3 American Music Award nominations; 5 RIAA Gold albums, 1 Platinum",
    url_website: "https://www.jeremycamp.com/",
    url_wiki: "https://en.wikipedia.org/wiki/Jeremy_Camp",
    url_youtube: "https://www.youtube.com/@JeremyCampMusic",
    url_apple_music: "https://music.apple.com/us/artist/jeremy-camp/574264",
    url_spotify: "https://open.spotify.com/artist/5wpEBloInversG3zp3CVAk",
    photo_url: null,
    status: "draft",
  },
  {
    name: "NONAH",
    type: "band",
    founded_year: 2013,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "NONAH is a pop worship band comprised of husband-and-wife duo Wes and Callie Strunk alongside producer and multi-instrumentalist Nate Alan. They began making music together in their North Carolina apartment around 2013 before relocating to Nashville. Their debut EP Jump garnered over ten million streams and earned them their first appearance in the top 30 of Billboard's Christian Airplay Chart. The band creates music rooted in worship and encounter with Jesus, blending pop production with heartfelt devotional lyrics.",
    style: "Pop worship, contemporary Christian pop, electronic worship",
    awards: null,
    url_website: "https://nonahmusic.com/",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@nonahmusic",
    url_apple_music: "https://music.apple.com/us/artist/nonah/1482469218",
    url_spotify: "https://open.spotify.com/artist/76SJxLztAMHPMieGTNZPeI",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Meredith Andrews",
    type: "solo",
    founded_year: 2005,
    location: "Nashville, Tennessee",
    church_label: "The Belonging Co / Curb Records",
    bio: "Meredith Frances Andrews is a contemporary Christian music artist, songwriter, and worship leader born on January 19, 1983, in Wilson, North Carolina. She attended Liberty University in Virginia and launched her independent recording career with Mesmerized in 2005. She is a two-time GMA Dove Award winner, receiving Praise and Worship Album of the Year and Worship Song of the Year for 'How Great Is the Love.' Her songs 'Open Up the Heavens,' 'Not for a Moment (After All),' and 'Spirit of the Living God' are widely sung in churches across America. She currently leads worship at The Belonging Co in Nashville.",
    style: "Contemporary worship, pop worship, congregational praise",
    awards: "2 GMA Dove Awards (Praise and Worship Album of the Year; Worship Song of the Year for 'How Great Is the Love')",
    url_website: "https://meredithandrews.com/",
    url_wiki: "https://en.wikipedia.org/wiki/Meredith_Andrews",
    url_youtube: "https://www.youtube.com/@meredithandrews",
    url_apple_music: "https://music.apple.com/us/artist/meredith-andrews/200726237",
    url_spotify: "https://open.spotify.com/artist/6qk2W9h3eE5UtPJlIatzsY",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Tiffany Hudson",
    type: "solo",
    founded_year: 2021,
    location: "Charlotte, North Carolina",
    church_label: "Elevation Church / Elevation Worship",
    bio: "Tiffany Hudson is an American worship leader, songwriter, and recording artist born on July 23, 1995, best known as a member of the Grammy Award-winning collective Elevation Worship at Elevation Church in Charlotte, North Carolina. She is an award-winning songwriter behind hits like 'Graves Into Gardens,' 'Wait On You,' and 'Never Lost,' and is known for leading songs such as 'More Than Able' and 'SO BE IT.' As part of Elevation Worship she has contributed to a Grammy Award win, two Billboard Music Awards, and nine GMA Dove Awards. She released her solo debut album Hidden Here in July 2023.",
    style: "Contemporary worship, gospel-influenced worship, soulful praise",
    awards: "Grammy Award (as part of Elevation Worship / Old Church Basement); 2 Billboard Music Awards; 9 GMA Dove Awards",
    url_website: "https://www.tiffanyhudsonmusic.com/",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@tiffanyhudson",
    url_apple_music: "https://music.apple.com/us/artist/tiffany-hudson/1557087901",
    url_spotify: "https://open.spotify.com/artist/0F58iilfZWiLrxyhsVOdQV",
    photo_url: null,
    status: "draft",
  },
  {
    name: "We Are Messengers",
    type: "band",
    founded_year: 2015,
    location: "Monaghan, Ireland / Nashville, Tennessee",
    church_label: "Curb | Word Entertainment",
    bio: "We Are Messengers is an Irish-American contemporary Christian music band formed in Monaghan, Ireland, in 2015, led by vocalist and songwriter Darren Mulligan, a former atheist who converted to Christianity at age 27 inspired by his wife Heidi's faith. After signing with Word Records, the band relocated to Nashville. Their 2016 self-titled debut album peaked at number ten on Billboard's Top Christian Albums chart. They have earned eleven consecutive top-ten radio singles including the multi-format number-one hit 'Come What May' and the RIAA Gold-certified 'Maybe It's Ok.'",
    style: "Contemporary Christian, alternative rock worship, anthemic pop rock, Irish-influenced CCM",
    awards: "GMA Dove Award nomination for New Artist of the Year; RIAA Gold certification ('Maybe It's Ok'); K-LOVE Fan Award nominations",
    url_website: "https://wearemessengersmusic.com/",
    url_wiki: "https://en.wikipedia.org/wiki/We_Are_Messengers",
    url_youtube: "https://www.youtube.com/@wearemessengers",
    url_apple_music: "https://music.apple.com/us/artist/we-are-messengers/1065671607",
    url_spotify: "https://open.spotify.com/artist/5WcisvYoq6332gCUX039Jd",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jesus Image",
    type: "band",
    founded_year: 2007,
    location: "Orlando, Florida",
    church_label: "Jesus Image Church",
    bio: "Jesus Image is an American charismatic, non-denominational Christian ministry and worship movement based in Orlando, Florida, founded in 2007 by evangelist Michael Koulianos and his wife Jessica. What began as an itinerant ministry has grown into a local church, a ministry training program called Jesus School, and large-scale worship conferences that draw thousands of attendees. Their worship music, including the viral hit 'Yeshua (Live)' with over 33 million Spotify streams, has become widely adopted in charismatic and revival-themed worship settings worldwide.",
    style: "Charismatic worship, spontaneous prophetic worship, live revival worship, soaking worship",
    awards: null,
    url_website: "https://jesusimage.tv/",
    url_wiki: "https://en.wikipedia.org/wiki/Jesus_Image",
    url_youtube: "https://www.youtube.com/@jesusimage",
    url_apple_music: "https://music.apple.com/us/artist/jesus-image/1616714364",
    url_spotify: "https://open.spotify.com/artist/47UT3dPXB5ttLBnyM76GQc",
    photo_url: null,
    status: "draft",
  },

  // === BATCH 3: Citizens, Young Oceans, Jervis Campbell, Tenth Avenue North, Influencers, Apollo LTD, David Leonard, Sovereign Grace Music ===
  {
    name: "Citizens",
    type: "band",
    founded_year: 2011,
    location: "Seattle, Washington",
    church_label: "Mars Hill Church / Anotherland",
    bio: "Citizens, formerly known as Citizens & Saints, is an American Christian rock band formed in 2011 in Seattle, Washington. Led by vocalist and guitarist Zach Bolen, the band originated as a worship project at Mars Hill Church. After Mars Hill's dissolution in 2014, the band continued independently, releasing albums through Humble Beast and later signing with Anotherland, an independent label founded by Hillsong's Joel Houston. Their sound blends alternative rock, post-punk, and electronic indie pop with faith-driven lyrics.",
    style: "Alternative rock, post-punk, indie electronic, worship",
    awards: null,
    url_website: "https://www.wearecitizens.net",
    url_wiki: "https://en.wikipedia.org/wiki/Citizens_(band)",
    url_youtube: "https://www.youtube.com/@citizensmusic",
    url_apple_music: "https://music.apple.com/us/artist/citizens/598475199",
    url_spotify: "https://open.spotify.com/artist/3e7KVnSiZjsBkReSv0L6db",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Young Oceans",
    type: "band",
    founded_year: 2012,
    location: "Brooklyn, New York",
    church_label: "Trinity Grace Church",
    bio: "Young Oceans is a meditative Christian art-rock project led by songwriter and worship leader Eric Marshall, originating as a collective of artists affiliated with Trinity Grace Church in Brooklyn, New York. Their self-titled debut album in 2012 was named a Top 10 album of the year by RELEVANT Magazine. The project blends deeply contemplative worship with Eno-inspired atmospherics, standing at the intersection of praise music and art rock.",
    style: "Ambient art rock, contemplative worship, neo-alternative, meditative",
    awards: null,
    url_website: "https://www.youngoceans.com",
    url_wiki: "https://en.wikipedia.org/wiki/Young_Oceans",
    url_youtube: "https://www.youtube.com/@youngoceans",
    url_apple_music: "https://music.apple.com/us/artist/young-oceans/513397875",
    url_spotify: "https://open.spotify.com/artist/41crVXG3GeS8TmyWEaPZVr",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jervis Campbell",
    type: "solo",
    founded_year: 2018,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "Jervis Campbell is a CCM singer-songwriter originally from Charlotte, North Carolina, who relocated to Nashville in 2017. His music wraps a warm vocal style in a blend of folk, pop, soul, and worship, drawing comparisons to artists like The Avett Brothers and Nathaniel Rateliff. He first gained traction with the 2019 single 'Garden' and released his debut full-length album Onward & Upward in 2021. His songs are deeply personal prayers set to strings-driven melodies.",
    style: "Folk, soul, CCM, acoustic worship, indie pop",
    awards: null,
    url_website: "https://www.jerviscampbell.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@jerviscampbell",
    url_apple_music: "https://music.apple.com/us/artist/jervis-campbell/1367246006",
    url_spotify: "https://open.spotify.com/artist/31Bh5G3Q9JzwqPpHDLIQtW",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Tenth Avenue North",
    type: "band",
    founded_year: 2000,
    location: "West Palm Beach, Florida",
    church_label: "Reunion Records / Provident Label Group",
    bio: "Tenth Avenue North is an American CCM band formed in 2000 by Mike Donehey and Jason Jamison while attending Palm Beach Atlantic University in West Palm Beach, Florida. They achieved major success with their 2008 debut Over and Underneath, featuring the platinum-certified single 'By Your Side,' which became one of the top Christian songs of the decade. The band won GMA Dove Awards for New Artist of the Year (2009) and Song of the Year (2010). After announcing their farewell in 2020, the band reunited in late 2023 with founding frontman Mike Donehey.",
    style: "CCM, pop rock, worship pop, adult contemporary Christian",
    awards: "GMA Dove Award: New Artist of the Year (2009), Song of the Year (2010), Short Form Music Video of the Year (2012)",
    url_website: "https://www.tenthavenuenorth.com",
    url_wiki: "https://en.wikipedia.org/wiki/Tenth_Avenue_North",
    url_youtube: "https://www.youtube.com/@tenthavenuenorth",
    url_apple_music: "https://music.apple.com/us/artist/tenth-avenue-north/156877492",
    url_spotify: "https://open.spotify.com/artist/7v35CkHBaT1SStgQHl95a0",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Influencers Worship",
    type: "band",
    founded_year: 2017,
    location: "Adelaide, Australia",
    church_label: "Influencers Church (now Futures Church)",
    bio: "Influencers Worship (now rebranded as Futures) is the worship movement of Influencers Church, a global Pentecostal church founded in Adelaide, Australia with campuses across Australia and the American South. Formed in 2017, the collective burst onto the scene with the debut single 'Imaginations,' which topped the iTunes Australian inspirational chart and broke the U.S. top 10. Their 2019 live debut album Just the Cross cemented their reputation for uplifting worship ballads. The church and worship movement rebranded to Futures in 2023.",
    style: "Contemporary worship, CCM pop, praise and worship",
    awards: null,
    url_website: "https://www.futuresworship.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@FuturesWorship",
    url_apple_music: "https://music.apple.com/us/artist/influencers-worship/300324684",
    url_spotify: "https://open.spotify.com/artist/6CZGjSCwsv967PAK4MfqC3",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Apollo LTD",
    type: "band",
    founded_year: 2015,
    location: "Nashville, Tennessee",
    church_label: "Residence Music / Centricity Music",
    bio: "Apollo LTD is a Nashville-based CCM and alternative-pop duo consisting of Jordan Phillips and Adam Stark, who met in 2004 as roommates at Belmont University. After years performing together in other projects, the duo launched Apollo LTD in 2015 with an independent self-titled EP. They signed to Residence Music, an imprint of Centricity Music, in 2017 and scored their first Top 40 hit with their debut full-length Out of Body. Their cinematic, synth-driven sound blends electro-pop with spiritually tender songwriting.",
    style: "Alternative pop, electro-pop, CCM, synth-driven rock",
    awards: "GMA Dove Award nomination for Rock/Contemporary Album of the Year",
    url_website: "https://weareapolloltd.com",
    url_wiki: "https://en.wikipedia.org/wiki/Apollo_LTD",
    url_youtube: "https://www.youtube.com/@ApolloLTD",
    url_apple_music: "https://music.apple.com/us/artist/apollo-ltd/1054429487",
    url_spotify: "https://open.spotify.com/artist/2H3EMYFS69dhMmrX9JTkZp",
    photo_url: null,
    status: "draft",
  },
  {
    name: "David Leonard",
    type: "solo",
    founded_year: 2019,
    location: "Nashville, Tennessee",
    church_label: "Provident Label Group / Integrity Music",
    bio: "David Leonard is a Grammy-nominated and GMA Dove Award-winning Christian singer-songwriter and producer from southeast Arkansas who rose to prominence as one half of the acclaimed worship duo All Sons & Daughters alongside Leslie Jordan. The duo was birthed from Journey Church in Franklin, Tennessee in 2009, releasing beloved songs like 'Great Are You Lord' and 'All The Poor and Powerless' before disbanding in 2018. Leonard launched his solo career in 2019 with the critically acclaimed album The Wait on Integrity Music.",
    style: "Worship folk-pop, CCM, acoustic worship, singer-songwriter",
    awards: "GMA Dove Award-winning producer; Grammy-nominated (All Sons & Daughters)",
    url_website: "https://www.davidleonardmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/David_Leonard_(singer)",
    url_youtube: "https://www.youtube.com/@davidleonard",
    url_apple_music: "https://music.apple.com/us/artist/david-leonard/1447310166",
    url_spotify: "https://open.spotify.com/artist/2r9qoFx4EhGP8RYFQ4eMIE",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Sovereign Grace Music",
    type: "band",
    founded_year: 1984,
    location: "Louisville, Kentucky",
    church_label: "Sovereign Grace Churches",
    bio: "Sovereign Grace Music is the worship music ministry of Sovereign Grace Churches, producing Christ-exalting congregational songs since 1984. Directed by Bob Kauflin, a former member of the Christian band Glad, the ministry is known for theologically rich, doctrinally grounded hymns and worship songs drawn directly from Scripture. Their catalog includes beloved modern hymns like 'Behold Our God' and albums such as Risen and From Age to Age, which charted on Billboard's Top Christian Albums. Their songs are translated into approximately 22 languages.",
    style: "Hymn-based worship, reformed theology worship, congregational singing",
    awards: null,
    url_website: "https://sovereigngracemusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Sovereign_Grace_Churches",
    url_youtube: "https://www.youtube.com/@SovereignGraceMusic",
    url_apple_music: "https://music.apple.com/us/artist/sovereign-grace-music/45129703",
    url_spotify: "https://open.spotify.com/artist/6MYKRhEIKscR8qdGlvpk9y",
    photo_url: null,
    status: "draft",
  },

  // === BATCH 4: Ryan Ellis, William Murphy, Olivia Lane, Andrew Ripp, Austin French, Plumb, Iron Bell Music ===
  {
    name: "Ryan Ellis",
    type: "solo",
    founded_year: 2014,
    location: "Orange, California",
    church_label: "Provident Label Group / Essential Worship",
    bio: "Ryan Ellis is a worship leader, songwriter, and former U.S. Navy veteran who served five years including a tour in Afghanistan. Before music ministry, he was a founding member of the Jabbawockeez hip-hop dance crew. After a personal encounter with Jesus, he became worship pastor at Isla Vista Upper Room in California and joined the Housefires Gospel Community. His single 'Heart of the Father' amassed over 34 million streams, and he penned Chris Tomlin's 'Resurrection Power,' earning an ASCAP 'Most Performed Song 2018' award.",
    style: "Contemporary worship, pop, R&B-infused praise music",
    awards: "ASCAP Most Performed Song 2018, GMA Dove Award nomination",
    url_website: "https://ryanellismusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Ryan_Ellis_(singer)",
    url_youtube: "https://www.youtube.com/@RyanEllisMusic",
    url_apple_music: "https://music.apple.com/us/artist/ryan-ellis/397646802",
    url_spotify: "https://open.spotify.com/artist/7mkCeiRcySEQSSAMYbud5C",
    photo_url: null,
    status: "draft",
  },
  {
    name: "William Murphy",
    type: "solo",
    founded_year: 2005,
    location: "Atlanta, Georgia",
    church_label: "dReam Center Church of Atlanta / Motown Gospel",
    bio: "Bishop William Murphy III is a Grammy-nominated gospel recording artist, pastor, and bishop born in Detroit, Michigan. He is the founder and lead pastor of the dReam Center Church of Atlanta and serves as presiding bishop of worship for the Full Gospel Baptist Church Fellowship. His breakout song 'Praise Is What I Do' became a modern gospel standard, and his 2013 live album 'God Chaser' earned a Grammy nomination for Best Gospel Album. He has consistently charted on Billboard's Gospel charts.",
    style: "Traditional and contemporary gospel, praise and worship, urban CCM",
    awards: "Grammy nomination for Best Gospel Album (God Chaser, 2013), Stellar Award winner, multiple Dove Award nominations",
    url_website: "https://www.williammurphy.org",
    url_wiki: "https://en.wikipedia.org/wiki/Bishop_William_Murphy_III",
    url_youtube: "https://www.youtube.com/@williammurphy",
    url_apple_music: "https://music.apple.com/us/artist/william-murphy/29539078",
    url_spotify: "https://open.spotify.com/artist/1FQJqgKQDNLWfeLBQoQLmD",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Olivia Lane",
    type: "solo",
    founded_year: 2013,
    location: "Nashville, Tennessee",
    church_label: "BEC Recordings",
    bio: "Olivia Lane is a Houston-raised, Nashville-based singer-songwriter born July 26, 1991. Originally a country music artist, she experienced a dramatic conversion to Christianity in 2018. Her viral TikTok posts in 2021 sharing her 'atheist to amen' journey propelled her song 'Woman at the Well' to massive acclaim, leading to her transition into CCM. She is now a morning host on SiriusXM's The Message (Channel 63) and released her first faith-based album 'Songs About Jesus' in 2025.",
    style: "Contemporary Christian pop, acoustic singer-songwriter, country-influenced CCM",
    awards: null,
    url_website: "https://www.olivialane.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@olivialanemusic",
    url_apple_music: "https://music.apple.com/us/artist/olivia-lane/886284796",
    url_spotify: "https://open.spotify.com/artist/3Og5as5vV5n1iTR5iaNNZ6",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Andrew Ripp",
    type: "solo",
    founded_year: 2005,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "Andrew Ripp is a Grammy-nominated singer-songwriter born August 24, 1982, in Palatine, Illinois, now based in Nashville, Tennessee. He initially found success in mainstream pop before transitioning to Christian music after a spiritual awakening. His 2020 single 'Jericho' became a number-one hit on Billboard's Christian Airplay chart, and he earned a Grammy nomination for co-writing Zach Williams' 'Rescue Story.' He has released seven studio albums blending pop, soul, and roots-rock with faith-driven lyrics.",
    style: "CCM, pop-rock, acoustic soul, singer-songwriter",
    awards: "Grammy nomination for Best Contemporary Christian Music Song (Rescue Story, 2020)",
    url_website: "https://www.andrewripp.com",
    url_wiki: "https://en.wikipedia.org/wiki/Andrew_Ripp",
    url_youtube: "https://www.youtube.com/@andrewripp",
    url_apple_music: "https://music.apple.com/us/artist/andrew-ripp/129425078",
    url_spotify: "https://open.spotify.com/artist/7oAskcd3mX9ZzxMPFHYqoN",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Austin French",
    type: "solo",
    founded_year: 2017,
    location: "Nashville, Tennessee",
    church_label: "Fair Trade Services",
    bio: "Austin Bryan French is a contemporary Christian musician born February 13, 1994, in Cordele, Georgia. Raised as the son of a worship pastor and music teacher, he began leading worship at Journey Church in Tifton, GA at age 18. In 2014, he was the runner-up on ABC's 'Rising Star.' His 2017 debut single 'Freedom Hymn' peaked at No. 8 on Billboard's Hot Christian Songs chart, and his debut album 'Wide Open' (2018) charted on Billboard's Top Christian Albums.",
    style: "Christian pop, contemporary worship, soul-influenced CCM",
    awards: null,
    url_website: "https://www.austinfrenchmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Austin_French",
    url_youtube: "https://www.youtube.com/@austinfrench",
    url_apple_music: "https://music.apple.com/us/artist/austin-french/894074776",
    url_spotify: "https://open.spotify.com/artist/5m8b1Ofn4kNkzRV84GopBU",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Plumb",
    type: "solo",
    founded_year: 1997,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "Plumb is the stage name of Tiffany Arbuckle Lee, born March 9, 1975, in Indianapolis, Indiana. She moved to Nashville before her 21st birthday and worked as a background singer for Bill Gaither and Amy Grant before landing a CCM record deal in 1997. She has sold over 500,000 albums and two million singles worldwide, co-written songs for artists including Michelle Branch, Mandisa, and Mandy Moore, and is known for deeply personal songs like 'Cut' and 'Need You Now.' She is a Dove Award-winning artist and author of two books.",
    style: "CCM, pop-rock, electronic pop, alternative Christian",
    awards: "GMA Dove Award winner",
    url_website: "https://www.plumbmusic.net",
    url_wiki: "https://en.wikipedia.org/wiki/Plumb_(singer)",
    url_youtube: "https://www.youtube.com/@plumbmusic",
    url_apple_music: "https://music.apple.com/us/artist/plumb/5360200",
    url_spotify: "https://open.spotify.com/artist/2tbxcCCM7A71cmkzuB8lyH",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Iron Bell Music",
    type: "band",
    founded_year: 2009,
    location: "Louisville, Kentucky",
    church_label: "Iron Bell Ministries / Essential Worship",
    bio: "Iron Bell Music is a worship collective born out of Iron Bell Ministries in Louisville, Kentucky. What began in 2009 as a small worship gathering in a home grew into Worship Nights, where hundreds gather at the Iron Bell barn. The group is built around primary songwriters and multi-instrumentalists Stephen McWhirter, Joel Gerdis, and Josh Glauber. They released their debut album 'God That Saves' via Essential Worship in 2017, followed by 'Glory to Glory' in 2018. Frontman Stephen McWhirter draws from his powerful testimony of recovery from addiction.",
    style: "Contemporary worship, CCM, congregational praise",
    awards: null,
    url_website: "https://ironbellmusic.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@IronBellMusic",
    url_apple_music: "https://music.apple.com/us/artist/iron-bell-music/1137246118",
    url_spotify: "https://open.spotify.com/artist/53D1D9DDZojMCL9XLsKCmK",
    photo_url: null,
    status: "draft",
  },
];

async function seedArtists() {
  let inserted = 0;
  let skipped = 0;

  for (const artist of artists) {
    const { data: existing } = await supabase
      .from("artists")
      .select("id")
      .eq("name", artist.name)
      .limit(1);

    if (existing && existing.length > 0) {
      console.log(`SKIP (exists): ${artist.name}`);
      skipped++;
      continue;
    }

    const { error } = await supabase.from("artists").insert(artist);

    if (error) {
      console.error(`ERROR ${artist.name}:`, error.message);
    } else {
      console.log(`INSERTED: ${artist.name}`);
      inserted++;
    }
  }

  console.log(`\nDone! Inserted: ${inserted}, Skipped: ${skipped}, Total: ${artists.length}`);
}

seedArtists();
