import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

type ArtistSeed = {
  name: string;
  type: "band" | "solo";
  founded_year: number | null;
  location: string | null;
  church_label: string | null;
  bio: string;
  style: string;
  awards: string | null;
  url_website: string | null;
  url_wiki: string | null;
  url_youtube: string | null;
  url_apple_music: string | null;
  url_spotify: string | null;
  photo_url: string | null;
  status: "draft";
};

const artists: ArtistSeed[] = [
  // === BANDS ===
  {
    name: "Hillsong UNITED",
    type: "band",
    founded_year: 1998,
    location: "Sydney, Australia",
    church_label: "Hillsong Church",
    bio: "Hillsong UNITED is the youth-born worship band from Hillsong Church in Sydney, Australia. Formed in 1998, the group became a global phenomenon with anthems like 'Oceans (Where Feet May Fail),' which spent a record-breaking 61 weeks atop the Billboard Hot Christian Songs chart. Led over the years by Joel Houston and Taya, UNITED's sound fuses arena-scale worship with indie rock and electronic textures. Their live recordings from world tours have defined a generation's worship vocabulary, making them arguably the most commercially successful worship act in history.",
    style: "Arena worship, indie rock-influenced, electronic textures, anthemic builds",
    awards: "Multiple ARIA Awards, GMA Dove Awards, Billboard Music Award nominations",
    url_website: "https://hillsongunited.com",
    url_wiki: "https://en.wikipedia.org/wiki/Hillsong_United",
    url_youtube: "https://www.youtube.com/@hillsongunited",
    url_apple_music: "https://music.apple.com/us/artist/hillsong-united/267089413",
    url_spotify: "https://open.spotify.com/artist/76iffaU2RUjFkSUBqt6UjI",
    photo_url: null, status: "draft",
  },
  {
    name: "Hillsong Young & Free",
    type: "band",
    founded_year: 2012,
    location: "Sydney, Australia",
    church_label: "Hillsong Church",
    bio: "Hillsong Young & Free is the youth-oriented worship movement from Hillsong Church, launched in 2012. They brought electronic dance music and pop production into worship, appealing to a younger demographic. Songs like 'This Is Living' and 'P E A C E' showcase their vibrant, festival-style worship approach. The group represents Hillsong's commitment to reaching every generation with relevant musical expression while maintaining authentic worship content.",
    style: "Electronic pop worship, EDM-influenced, youthful energy, festival-style",
    awards: "GMA Dove Award nominations, ARIA nominations",
    url_website: "https://hillsong.com/youngandfree",
    url_wiki: "https://en.wikipedia.org/wiki/Hillsong_Young_%26_Free",
    url_youtube: "https://www.youtube.com/@hillsongyoungandfree",
    url_apple_music: "https://music.apple.com/us/artist/hillsong-young-free/717703190",
    url_spotify: "https://open.spotify.com/artist/2FKWNmZWDBZR4dE5KkLlMM",
    photo_url: null, status: "draft",
  },
  {
    name: "Passion",
    type: "band",
    founded_year: 1997,
    location: "Atlanta, Georgia",
    church_label: "Passion City Church",
    bio: "Passion is a worship movement founded by Louie Giglio in 1997, centered around the annual Passion Conference that draws tens of thousands of college students. The collective features rotating worship leaders including Kristian Stanfill, Melodie Malone, and Brett Younker. Songs like 'How Great Is Our God' (featuring Chris Tomlin), 'Even So Come,' and 'Glorious Day' have become worship standards. Passion's live albums consistently debut at the top of Christian charts, capturing the electric energy of their massive gatherings.",
    style: "Conference worship, anthemic pop-rock, large-scale congregational singing",
    awards: "Multiple GMA Dove Awards, Billboard chart-toppers",
    url_website: "https://passionmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Passion_Conferences",
    url_youtube: "https://www.youtube.com/@passionmusic",
    url_apple_music: "https://music.apple.com/us/artist/passion/3299556",
    url_spotify: "https://open.spotify.com/artist/4TSNSvplMkpoJHRVCzYPBb",
    photo_url: null, status: "draft",
  },
  {
    name: "North Point Worship",
    type: "band",
    founded_year: 2012,
    location: "Alpharetta, Georgia",
    church_label: "North Point Community Church",
    bio: "North Point Worship is the worship ministry of Andy Stanley's North Point Community Church in Alpharetta, Georgia. The team creates accessible, well-produced worship music designed for congregational use. Their songs 'Death Was Arrested' and 'Abundantly More' have gained significant traction in churches nationwide. The collective prioritizes singability and theological clarity, reflecting North Point's mission to create environments where people can encounter God.",
    style: "Congregational pop worship, accessible melodies, polished production",
    awards: "GMA Dove Award nominations",
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@northpointworship",
    url_apple_music: "https://music.apple.com/us/artist/north-point-worship/905628644",
    url_spotify: "https://open.spotify.com/artist/6B2xhfcaLMPSmzBAFxjt7r",
    photo_url: null, status: "draft",
  },
  {
    name: "Gateway Worship",
    type: "band",
    founded_year: 2003,
    location: "Southlake, Texas",
    church_label: "Gateway Church",
    bio: "Gateway Worship is the worship ministry of Gateway Church in Southlake, Texas, one of the largest churches in the United States. The team has featured prominent worship leaders including Kari Jobe and Cody Carnes. Their music spans from intimate devotional songs to powerful corporate worship anthems. Gateway Worship emphasizes the presence of God and has produced numerous songs adopted by churches worldwide, including 'Spirit of the Living God' and 'Revelation Song.'",
    style: "Spirit-led worship, intimate to anthemic range, Texas-rooted",
    awards: "GMA Dove Award nominations",
    url_website: "https://gatewayworship.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@gatewayworship",
    url_apple_music: "https://music.apple.com/us/artist/gateway-worship/268513037",
    url_spotify: "https://open.spotify.com/artist/1u8B3LnMBQwHAH2JYmBM9Y",
    photo_url: null, status: "draft",
  },
  {
    name: "Planetshakers",
    type: "band",
    founded_year: 1997,
    location: "Melbourne, Australia",
    church_label: "Planetshakers Church",
    bio: "Planetshakers is an Australian worship band from Planetshakers Church in Melbourne, founded by Russell and Sam Evans in 1997. Known for their high-energy worship style and youth-focused conferences, they have built a global following particularly strong in Asia-Pacific. Their music combines pop-rock worship with charismatic intensity. Songs like 'Nothing Is Impossible' and 'The Anthem' have become favorites in energetic worship settings worldwide.",
    style: "High-energy pop-rock worship, charismatic, youth conference atmosphere",
    awards: null,
    url_website: "https://planetshakers.com",
    url_wiki: "https://en.wikipedia.org/wiki/Planetshakers",
    url_youtube: "https://www.youtube.com/@Planetshakers",
    url_apple_music: "https://music.apple.com/us/artist/planetshakers/65120042",
    url_spotify: "https://open.spotify.com/artist/1BCig5VGMWsOPByxSwK69n",
    photo_url: null, status: "draft",
  },
  {
    name: "Israel & New Breed",
    type: "band",
    founded_year: 1995,
    location: "Houston, Texas",
    church_label: null,
    bio: "Israel & New Breed is a worship collective led by Israel Houghton, blending gospel, rock, jazz, reggae, and Latin influences into a unique multicultural worship expression. Formed in 1995, the group has won multiple Grammy Awards and GMA Dove Awards. Songs like 'You Are Good,' 'Friend of God,' and 'Te Amo' exemplify their genre-crossing approach. Houghton's vision for worship that transcends racial and cultural boundaries has profoundly influenced the modern worship movement's embrace of diversity.",
    style: "Multicultural fusion worship — gospel, rock, jazz, Latin, reggae",
    awards: "6 Grammy Awards, multiple GMA Dove Awards",
    url_website: null,
    url_wiki: "https://en.wikipedia.org/wiki/Israel_Houghton",
    url_youtube: "https://www.youtube.com/@IsraelAndNewBreed",
    url_apple_music: "https://music.apple.com/us/artist/israel-new-breed/5592194",
    url_spotify: "https://open.spotify.com/artist/3KH1PmrGb4nOVJLR2kxVEd",
    photo_url: null, status: "draft",
  },
  {
    name: "The Belonging Co",
    type: "band",
    founded_year: 2014,
    location: "Nashville, Tennessee",
    church_label: "The Belonging Co Church",
    bio: "The Belonging Co is a worship collective from the Nashville-based church of the same name, founded by Henry and Alex Seeley in 2014. Their music is characterized by lush production, emotive arrangements, and powerful vocal performances. Featuring worship leaders like Meredith Andrews, Andrew Holt, and Kari Jobe (who is part of the church community), their songs 'All The Earth' and 'Isn't He' have gained significant streaming numbers. The Belonging Co represents Nashville's growing influence in the worship music world.",
    style: "Cinematic worship, lush production, emotive vocal performances",
    awards: null,
    url_website: "https://thebelongingco.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@TheBelongingCo",
    url_apple_music: "https://music.apple.com/us/artist/the-belonging-co/1178093498",
    url_spotify: "https://open.spotify.com/artist/21X8gHvHUkJJrdBrdXiFuL",
    photo_url: null, status: "draft",
  },
  {
    name: "for KING & COUNTRY",
    type: "band",
    founded_year: 2007,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "for KING & COUNTRY is an Australian-American Christian pop duo consisting of brothers Joel and Luke Smallbone. Formed in 2007 and based in Nashville, they have become one of the biggest acts in Christian music, known for theatrical live shows and cinematic production. Hits like 'joy.,' 'God Only Knows,' and 'Burn the Ships' have crossed over to mainstream audiences. They won four Grammy Awards and have sold out arenas worldwide. Their sister is Grammy-winning artist Rebecca St. James.",
    style: "Christian pop, cinematic production, theatrical live performance, anthemic",
    awards: "4 Grammy Awards, 7 GMA Dove Awards, Billboard Music Awards",
    url_website: "https://forkingandcountry.com",
    url_wiki: "https://en.wikipedia.org/wiki/For_King_%26_Country",
    url_youtube: "https://www.youtube.com/@faborKINGandCOUNTRY",
    url_apple_music: "https://music.apple.com/us/artist/for-king-country/431553181",
    url_spotify: "https://open.spotify.com/artist/4WNInXjgqXgNe7hGpMSxOn",
    photo_url: null, status: "draft",
  },
  {
    name: "Newsboys",
    type: "band",
    founded_year: 1985,
    location: "Mooloolaba, Australia",
    church_label: null,
    bio: "Newsboys are one of the most enduring bands in Christian music history, formed in 1985 in Queensland, Australia, and later relocating to Nashville. Over four decades, they have sold over 10 million albums with lineup changes that kept them relevant across generations. Led most notably by Peter Furler and later Michael Tait (formerly of DC Talk), their hits include 'God's Not Dead,' 'Born Again,' and 'We Believe.' The song 'God's Not Dead' inspired a successful film franchise. They remain a major touring act in the Christian market.",
    style: "Christian pop-rock, upbeat anthems, arena rock energy",
    awards: "5 GMA Dove Awards, multiple Grammy nominations, sold 10M+ albums",
    url_website: "https://newsboys.com",
    url_wiki: "https://en.wikipedia.org/wiki/Newsboys",
    url_youtube: "https://www.youtube.com/@Newsboys",
    url_apple_music: "https://music.apple.com/us/artist/newsboys/543655",
    url_spotify: "https://open.spotify.com/artist/3tlkkjCpVRa5bqGMWzfZkY",
    photo_url: null, status: "draft",
  },
  {
    name: "Skillet",
    type: "band",
    founded_year: 1996,
    location: "Memphis, Tennessee",
    church_label: null,
    bio: "Skillet is a Christian rock band formed in Memphis, Tennessee in 1996, led by husband-and-wife John and Korey Cooper. They are one of the best-selling Christian rock bands of all time, with over 13 million albums sold and 3 billion streams. Their 2009 album 'Awake' achieved double platinum status, driven by the hit 'Monster.' Skillet successfully bridges the gap between Christian and mainstream rock markets, performing at both Christian festivals and secular rock venues. Their music tackles themes of faith, struggle, and resilience with hard rock intensity.",
    style: "Christian hard rock, symphonic elements, industrial-tinged, crossover appeal",
    awards: "Grammy nominations, GMA Dove Awards, RIAA multi-platinum certifications",
    url_website: "https://skillet.com",
    url_wiki: "https://en.wikipedia.org/wiki/Skillet_(band)",
    url_youtube: "https://www.youtube.com/@sklofficialmusic",
    url_apple_music: "https://music.apple.com/us/artist/skillet/1750437",
    url_spotify: "https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu",
    photo_url: null, status: "draft",
  },
  {
    name: "We The Kingdom",
    type: "band",
    founded_year: 2018,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "We The Kingdom is a multigenerational family band from Nashville, featuring Ed Cash (prolific songwriter/producer), his daughter Franni Rae Cash Cain, her husband Martin Cash Cain, Scott Cash, and Andrew Bergthold. Formed in 2018, they quickly became one of the fastest-rising acts in Christian music. Their debut single 'Holy Water' was a massive hit, and 'God So Loved' became a modern worship staple. The group's authenticity and raw emotional delivery have resonated with audiences seeking genuine worship expression.",
    style: "Raw folk-rock worship, multigenerational, emotionally authentic, roots-influenced",
    awards: "GMA Dove Awards, Grammy nomination, Billboard #1 songs",
    url_website: "https://wethekingdom.com",
    url_wiki: "https://en.wikipedia.org/wiki/We_the_Kingdom",
    url_youtube: "https://www.youtube.com/@WeTheKingdom",
    url_apple_music: "https://music.apple.com/us/artist/we-the-kingdom/1460227657",
    url_spotify: "https://open.spotify.com/artist/7pKhkS7DjmDl3GNuqsj5AG",
    photo_url: null, status: "draft",
  },
  {
    name: "UPPERROOM",
    type: "band",
    founded_year: 2010,
    location: "Dallas, Texas",
    church_label: "UPPERROOM Church",
    bio: "UPPERROOM is a prayer and worship movement based in Dallas, Texas, born from a 24/7 prayer room model. Their worship is characterized by extended, spontaneous, Spirit-led sessions that can last for hours. Songs like 'Surrounded (Fight My Battles)' have crossed over into mainstream worship use, with the song being covered by Michael W. Smith. UPPERROOM represents a raw, unpolished approach to worship music that prioritizes encounter and prayer over production value, drawing young adults seeking authentic spiritual experience.",
    style: "Spontaneous prayer-room worship, raw and unpolished, extended sets, prophetic",
    awards: null,
    url_website: "https://upperroom.co",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@UPPERROOM",
    url_apple_music: "https://music.apple.com/us/artist/upperroom/1080498736",
    url_spotify: "https://open.spotify.com/artist/1JJx1BP3WtQFiMPWXIb9Bi",
    photo_url: null, status: "draft",
  },

  // === SOLO ARTISTS ===
  {
    name: "NF",
    type: "solo",
    founded_year: 2010,
    location: "Gladwin, Michigan",
    church_label: null,
    bio: "NF (Nathan John Feuerstein) is a rapper and singer from Gladwin, Michigan, who has achieved massive mainstream success while maintaining faith-influenced themes. His intensely personal lyrics address mental health, anxiety, and inner struggles with raw honesty. His album 'The Search' debuted at No. 1 on the Billboard 200 in 2019, outselling Chance the Rapper's release that same week. NF deliberately avoids profanity and explicit content without labeling himself strictly as a 'Christian rapper,' preferring to let his faith speak through authentic storytelling.",
    style: "Emotional hip-hop, introspective rap, cinematic production, no profanity",
    awards: "Billboard 200 #1 album, multiple platinum certifications",
    url_website: "https://nfrealmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/NF_(rapper)",
    url_youtube: "https://www.youtube.com/@NFREALMUSIC",
    url_apple_music: "https://music.apple.com/us/artist/nf/656391728",
    url_spotify: "https://open.spotify.com/artist/6fOMl44jA6Bo1PVPbWNziY",
    photo_url: null, status: "draft",
  },
  {
    name: "TobyMac",
    type: "solo",
    founded_year: 2001,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "TobyMac (Kevin Michael McKeehan) is a Christian music pioneer who first gained fame as a member of the groundbreaking trio DC Talk in the late 1980s. His solo career, launched in 2001, has been equally successful, blending pop, hip-hop, rock, and electronic music into an energetic, genre-defying sound. Hits like 'I Just Need U,' 'Feel It,' and 'Speak Life' showcase his ability to evolve with musical trends while maintaining uplifting, faith-centered messages. With over 11 million albums sold across his career, TobyMac remains one of Christian music's most consistent hitmakers.",
    style: "Christian pop-hip-hop fusion, energetic, genre-blending, family-friendly",
    awards: "7 Grammy Awards, multiple GMA Dove Awards, sold 11M+ albums",
    url_website: "https://tobymac.com",
    url_wiki: "https://en.wikipedia.org/wiki/TobyMac",
    url_youtube: "https://www.youtube.com/@TobyMac",
    url_apple_music: "https://music.apple.com/us/artist/tobymac/5765478",
    url_spotify: "https://open.spotify.com/artist/6MDME20pz9RveH9rEXvrOM",
    photo_url: null, status: "draft",
  },
  {
    name: "Chandler Moore",
    type: "solo",
    founded_year: 2019,
    location: "Charleston, South Carolina",
    church_label: "Maverick City Music",
    bio: "Chandler Moore is a worship leader who has become one of the defining voices of modern worship through his work with Maverick City Music. His warm, soulful vocal delivery and gift for spontaneous worship have made songs like 'Jireh,' 'Man of Your Word,' and 'Million Little Miracles' global worship anthems. Moore's ability to seamlessly blend gospel, R&B, and contemporary worship has earned him Grammy recognition. He represents the new generation of worship leaders who prioritize diversity, authenticity, and musical excellence.",
    style: "Gospel-infused worship, soulful vocals, spontaneous and intimate, R&B-influenced",
    awards: "Grammy Award (with Maverick City Music), GMA Dove Awards",
    url_website: null,
    url_wiki: "https://en.wikipedia.org/wiki/Chandler_Moore",
    url_youtube: "https://www.youtube.com/@ChandlerMoore",
    url_apple_music: "https://music.apple.com/us/artist/chandler-moore/1452498076",
    url_spotify: "https://open.spotify.com/artist/3uNBhRn8VELREFnyhKgB6Z",
    photo_url: null, status: "draft",
  },
  {
    name: "Brooke Ligertwood",
    type: "solo",
    founded_year: 2002,
    location: "Sydney, Australia",
    church_label: "Hillsong Worship",
    bio: "Brooke Ligertwood (formerly Brooke Fraser) is a New Zealand-born singer-songwriter who became the primary worship leader and songwriter for Hillsong Worship. She wrote 'What A Beautiful Name,' which won the Grammy for Best Contemporary Christian Music Song and is one of the most-sung worship songs globally. Her dual career spans mainstream pop (as Brooke Fraser, with hits like 'Something in the Water' in New Zealand) and worship leadership. Ligertwood's songwriting combines theological depth with poetic elegance.",
    style: "Elegant worship songwriting, pop sensibility, theologically rich, globally accessible",
    awards: "Grammy Award for Best Contemporary Christian Music Song, NZ Music Awards",
    url_website: "https://brookeligertwood.com",
    url_wiki: "https://en.wikipedia.org/wiki/Brooke_Fraser",
    url_youtube: "https://www.youtube.com/@BrookeLigertwood",
    url_apple_music: "https://music.apple.com/us/artist/brooke-ligertwood/207327771",
    url_spotify: "https://open.spotify.com/artist/7rTFYdzfCbmqCtzkkYjvGl",
    photo_url: null, status: "draft",
  },
  {
    name: "Tasha Cobbs Leonard",
    type: "solo",
    founded_year: 2010,
    location: "Atlanta, Georgia",
    church_label: null,
    bio: "Tasha Cobbs Leonard is one of the most powerful voices in contemporary gospel music. Her 2013 hit 'Break Every Chain' became a defining anthem of the decade, and her album 'Grace' won the Grammy for Best Gospel/Contemporary Christian Music Performance. Cobbs Leonard's music sits at the intersection of traditional gospel and contemporary worship, making her equally at home in black church traditions and multiethnic worship settings. Her raw, anointed vocal delivery and heart for ministry have made her one of the most sought-after worship leaders in America.",
    style: "Contemporary gospel, powerful vocals, anointed worship ministry, bridge between traditions",
    awards: "Grammy Award, multiple GMA Dove Awards, Stellar Awards, Billboard #1",
    url_website: "https://tashacobbleonard.com",
    url_wiki: "https://en.wikipedia.org/wiki/Tasha_Cobbs_Leonard",
    url_youtube: "https://www.youtube.com/@TashaCobhLeonard",
    url_apple_music: "https://music.apple.com/us/artist/tasha-cobbs-leonard/551707683",
    url_spotify: "https://open.spotify.com/artist/6yVMObOy70uer7EFTYtmwi",
    photo_url: null, status: "draft",
  },
  {
    name: "Kirk Franklin",
    type: "solo",
    founded_year: 1992,
    location: "Fort Worth, Texas",
    church_label: null,
    bio: "Kirk Franklin is widely regarded as the greatest innovator in gospel music history. Since bursting onto the scene in 1992 with Kirk Franklin & The Family, he has consistently pushed the boundaries of gospel, incorporating hip-hop, pop, R&B, and rock elements. Hits like 'Stomp,' 'Revolution,' 'I Smile,' and 'Love Theory' have brought gospel to mainstream audiences. With 16 Grammy Awards, Franklin is the most awarded gospel artist of all time. He also hosts a syndicated radio show and has served as a mentor to countless emerging gospel artists.",
    style: "Genre-defying gospel — hip-hop, pop, R&B fusion, choir-driven, celebratory",
    awards: "16 Grammy Awards, GMA Dove Awards, Stellar Awards, NAACP Image Awards",
    url_website: "https://kirkfranklin.com",
    url_wiki: "https://en.wikipedia.org/wiki/Kirk_Franklin",
    url_youtube: "https://www.youtube.com/@kirkfranklin",
    url_apple_music: "https://music.apple.com/us/artist/kirk-franklin/85827",
    url_spotify: "https://open.spotify.com/artist/3bnJxRY0MXJmaPC1u7u2a8",
    photo_url: null, status: "draft",
  },
  {
    name: "Travis Greene",
    type: "solo",
    founded_year: 2007,
    location: "Columbia, South Carolina",
    church_label: "Forward City Church",
    bio: "Travis Greene is a pastor, worship leader, and songwriter known for his innovative approach to gospel music. His song 'Made A Way' became a viral sensation and earned him widespread recognition. As the pastor of Forward City Church in Columbia, South Carolina, Greene combines pastoral ministry with music that crosses generational and cultural boundaries. His live recordings capture energetic, Spirit-filled worship experiences. Albums like 'Crossover: Live from Music City' demonstrate his ability to blend gospel tradition with contemporary production.",
    style: "Contemporary gospel, innovative production, energetic live worship, pastoral",
    awards: "Grammy nominations, Stellar Awards, Billboard Gospel chart-toppers",
    url_website: "https://travisgreene.tv",
    url_wiki: "https://en.wikipedia.org/wiki/Travis_Greene",
    url_youtube: "https://www.youtube.com/@TravisGreeneTV",
    url_apple_music: "https://music.apple.com/us/artist/travis-greene/390966376",
    url_spotify: "https://open.spotify.com/artist/12VqsEHIalDN81Rtm4K7qs",
    photo_url: null, status: "draft",
  },
  {
    name: "Tamela Mann", type: "solo", founded_year: 1990, location: "Fort Worth, Texas", church_label: null,
    bio: "Tamela Mann is a gospel music powerhouse known for her stunning vocal range and emotive delivery. Originally a member of Kirk Franklin's choir, she later achieved massive solo success with 'Take Me to the King,' which became one of the biggest gospel songs of the 2010s. Beyond music, Mann is an accomplished actress, starring alongside her husband David Mann in multiple Tyler Perry productions and their own reality show. Her combination of gospel excellence and entertainment crossover has made her a beloved figure in the African American community.",
    style: "Traditional and contemporary gospel, powerhouse vocals, worship ballads",
    awards: "Grammy Award, multiple GMA Dove Awards, BET Awards, Stellar Awards",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/Tamela_Mann",
    url_youtube: "https://www.youtube.com/@TamelaMann", url_apple_music: "https://music.apple.com/us/artist/tamela-mann/82615997", url_spotify: "https://open.spotify.com/artist/5p0djlnp9p1tMfM1ELkYtb", photo_url: null, status: "draft",
  },
  {
    name: "Tauren Wells", type: "solo", founded_year: 2016, location: "Houston, Texas", church_label: null,
    bio: "Tauren Wells is a singer-songwriter and worship leader from Houston, Texas, formerly the frontman of the band Royal Tailor. His solo career has produced chart-topping hits including 'Hills and Valleys,' 'Known,' and 'Famous For (I Believe)' featuring Jenn Johnson. Wells' music blends pop production with worship lyrics, creating radio-friendly songs with spiritual depth. His energetic stage presence and vocal agility have made him a standout performer in the contemporary Christian music scene.",
    style: "Pop worship, dance-influenced, radio-friendly, energetic vocals",
    awards: "GMA Dove Awards including New Artist of the Year, Billboard chart success",
    url_website: "https://taurenwells.com", url_wiki: "https://en.wikipedia.org/wiki/Tauren_Wells",
    url_youtube: "https://www.youtube.com/@TaurenWells", url_apple_music: "https://music.apple.com/us/artist/tauren-wells/1170498817", url_spotify: "https://open.spotify.com/artist/4JTQpSwCkMYX0Hqbi1lmEX", photo_url: null, status: "draft",
  },
  {
    name: "Matthew West", type: "solo", founded_year: 2000, location: "Nashville, Tennessee", church_label: null,
    bio: "Matthew West is a singer-songwriter and storyteller who has built his career on turning real people's stories into powerful songs. His project 'The Story of Your Life' invited fans to submit personal stories, which he then set to music. Hits include 'Hello, My Name Is,' 'Broken Things,' and 'Truth Be Told.' West is a five-time ASCAP Christian Songwriter of the Year and has written songs for numerous other artists. He also authored several books and created a podcast exploring the intersection of faith and storytelling.",
    style: "Narrative-driven Christian pop, storytelling, accessible singer-songwriter",
    awards: "5x ASCAP Christian Songwriter of the Year, GMA Dove Awards, Grammy nominations",
    url_website: "https://matthewwest.com", url_wiki: "https://en.wikipedia.org/wiki/Matthew_West",
    url_youtube: "https://www.youtube.com/@MatthewWest", url_apple_music: "https://music.apple.com/us/artist/matthew-west/16815307", url_spotify: "https://open.spotify.com/artist/0LkBHYl0dmBLBJIhkMKDjP", photo_url: null, status: "draft",
  },
  {
    name: "Zach Williams", type: "solo", founded_year: 2016, location: "Jonesboro, Arkansas", church_label: null,
    bio: "Zach Williams is a Christian singer-songwriter from Jonesboro, Arkansas, whose debut single 'Chain Breaker' became a massive hit in 2016 and earned him a Grammy Award. After years in secular rock bands and struggling with addiction, Williams' redemption story gives his music an authenticity that resonates deeply. His southern rock-influenced sound sets him apart in Christian music, and songs like 'Old Church Choir,' 'There Was Jesus' (with Dolly Parton), and 'Less Like Me' have all been major hits.",
    style: "Southern rock-influenced Christian, gritty authentic vocals, redemption themes",
    awards: "2 Grammy Awards, GMA Dove Awards, Billboard #1 songs",
    url_website: "https://zachwilliamsmusic.com", url_wiki: "https://en.wikipedia.org/wiki/Zach_Williams_(musician)",
    url_youtube: "https://www.youtube.com/@ZachWilliams", url_apple_music: "https://music.apple.com/us/artist/zach-williams/1080577507", url_spotify: "https://open.spotify.com/artist/3Fje5RCPgbPHkpJqlzhvB3", photo_url: null, status: "draft",
  },
  {
    name: "Anne Wilson", type: "solo", founded_year: 2020, location: "Lexington, Kentucky", church_label: null,
    bio: "Anne Wilson is a singer-songwriter from Lexington, Kentucky, who emerged as one of Christian music's brightest new voices. She began singing publicly after the tragic death of her brother Jacob in a car accident, channeling her grief into her debut single 'My Jesus,' which went viral on TikTok and became one of the fastest-rising Christian songs in recent memory. Wilson blends country influences with pop-Christian sensibilities, and her authentic testimony has connected with millions of listeners.",
    style: "Christian country-pop, authentic testimony, Nashville-influenced, young female vocal",
    awards: "GMA Dove Award for New Artist of the Year, Billboard chart success",
    url_website: "https://annewilsonofficial.com", url_wiki: "https://en.wikipedia.org/wiki/Anne_Wilson_(singer)",
    url_youtube: "https://www.youtube.com/@AnneWilsonMusic", url_apple_music: "https://music.apple.com/us/artist/anne-wilson/1545484830", url_spotify: "https://open.spotify.com/artist/3KMIjTrUB4fDaVJfwWLkqx", photo_url: null, status: "draft",
  },
  {
    name: "Riley Clemmons", type: "solo", founded_year: 2017, location: "Nashville, Tennessee", church_label: null,
    bio: "Riley Clemmons is a pop-Christian artist from Nashville who signed a record deal at age 16. Her debut single 'Broken Prayers' and subsequent hits like 'Fighting for Me' and 'Keep On Hoping' showcase a polished pop sound with faith-based lyrics targeted at younger listeners. Clemmons represents the new generation of Christian artists who grew up with social media and streaming, building her audience through digital platforms while delivering authentic messages of hope and identity in Christ.",
    style: "Christian pop, youthful, social media-native, polished production",
    awards: null,
    url_website: "https://rileyclemmons.com", url_wiki: null,
    url_youtube: "https://www.youtube.com/@RileyClemmons", url_apple_music: "https://music.apple.com/us/artist/riley-clemmons/1213400511", url_spotify: "https://open.spotify.com/artist/7qexq4yMnNRMpJPmdK3cYJ", photo_url: null, status: "draft",
  },
  {
    name: "Dante Bowe", type: "solo", founded_year: 2019, location: "Savannah, Georgia", church_label: null,
    bio: "Dante Bowe is a singer-songwriter and former core member of Maverick City Music. His soulful voice and genre-blending approach — fusing gospel, R&B, and pop — helped define the Maverick City sound. Songs like 'Jireh' (with Chandler Moore and Elevation Worship) became massive worship anthems. After departing Maverick City, Bowe continued his solo career, exploring more R&B-leaning territory while maintaining his gospel roots. His artistry represents the evolving boundaries of what gospel music can sound like.",
    style: "Gospel R&B, soulful worship, genre-blending, contemporary urban gospel",
    awards: "Grammy Award (with Maverick City Music), GMA Dove Awards",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/Dante_Bowe",
    url_youtube: "https://www.youtube.com/@DanteBowe", url_apple_music: "https://music.apple.com/us/artist/dante-bowe/1361755693", url_spotify: "https://open.spotify.com/artist/3MX0s6ER3mdPv3p0K0iJwH", photo_url: null, status: "draft",
  },
  {
    name: "DOE", type: "solo", founded_year: 2020, location: "Los Angeles, California", church_label: null,
    bio: "DOE (Dominique Jones) is a singer-songwriter bringing a fresh R&B-gospel fusion to contemporary worship. Her music combines sultry, soulful vocals with lyrics of devotion and worship, creating a sound that feels both intimate and spiritually charged. Songs like 'When I Pray' and 'So Good' have introduced her unique voice to the gospel world. DOE represents the next wave of gospel artists who draw equally from secular R&B and church worship traditions, creating music that feels authentically both.",
    style: "R&B gospel fusion, intimate soulful vocals, modern worship with urban edge",
    awards: "Grammy nomination, GMA Dove Award nominations",
    url_website: null, url_wiki: null,
    url_youtube: "https://www.youtube.com/@DOEofficial", url_apple_music: "https://music.apple.com/us/artist/doe/1485069842", url_spotify: "https://open.spotify.com/artist/1aKT9kYW1sHlPnbOeYIq7h", photo_url: null, status: "draft",
  },
  {
    name: "Jonathan McReynolds", type: "solo", founded_year: 2012, location: "Chicago, Illinois", church_label: null,
    bio: "Jonathan McReynolds is a Grammy-winning gospel artist, songwriter, and professor from Chicago. Known for his acoustic guitar-driven gospel and thoughtful songwriting, McReynolds brings an intellectual and poetic approach to worship. His songs 'Not Lucky, I'm Loved,' 'Cycles,' and 'People' address real-life faith struggles with honesty and vulnerability. As a professor at Columbia College Chicago, he bridges the academic and ministry worlds. His stripped-back approach to gospel has earned him a devoted following among younger, thoughtful believers.",
    style: "Acoustic gospel, thoughtful songwriting, minimalist arrangements, poetic",
    awards: "2 Grammy Awards, Stellar Awards, GMA Dove Award nominations",
    url_website: "https://jonathanmcreynolds.com", url_wiki: "https://en.wikipedia.org/wiki/Jonathan_McReynolds",
    url_youtube: "https://www.youtube.com/@JonathanMcReynolds", url_apple_music: "https://music.apple.com/us/artist/jonathan-mcreynolds/555539429", url_spotify: "https://open.spotify.com/artist/5JxPaLLplwyumwTyD0bOXR", photo_url: null, status: "draft",
  },
  {
    name: "Tye Tribbett", type: "solo", founded_year: 2000, location: "Camden, New Jersey", church_label: null,
    bio: "Tye Tribbett is one of gospel music's most electrifying performers, known for his explosive energy and innovative musical arrangements. From Camden, New Jersey, Tribbett brings a raw, urban edge to gospel that has earned him Grammy Awards and a reputation as one of the most dynamic live performers in any genre. Songs like 'Victory,' 'What Can I Do,' and 'If He Did It Before' are gospel standards. His ability to command a stage with wild energy while maintaining deep spiritual conviction makes every Tye Tribbett performance unforgettable.",
    style: "High-energy gospel, urban edge, explosive live performance, innovative arrangements",
    awards: "2 Grammy Awards, Stellar Awards, BET Awards",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/Tye_Tribbett",
    url_youtube: "https://www.youtube.com/@TyeTribbett", url_apple_music: "https://music.apple.com/us/artist/tye-tribbett/5301866", url_spotify: "https://open.spotify.com/artist/5Rn9gOY4gP07cxbP0JMfJG", photo_url: null, status: "draft",
  },
  {
    name: "Lecrae", type: "solo", founded_year: 2004, location: "Houston, Texas", church_label: "Reach Records",
    bio: "Lecrae Moore is the most commercially successful Christian hip-hop artist in history. The Houston-based rapper founded Reach Records and has released multiple chart-topping albums, including 'Anomaly,' which debuted at No. 1 on the Billboard 200 in 2014 — a first for a Christian hip-hop album. Lecrae's music addresses faith, social justice, racial reconciliation, and personal struggle with unflinching honesty. He has been credited with legitimizing Christian hip-hop as a credible art form and opening doors for a generation of faith-based rappers.",
    style: "Christian hip-hop, socially conscious rap, introspective, culturally engaged",
    awards: "2 Grammy Awards, GMA Dove Awards, Billboard 200 #1, sold 3M+ albums",
    url_website: "https://lecrae.com", url_wiki: "https://en.wikipedia.org/wiki/Lecrae",
    url_youtube: "https://www.youtube.com/@Lecrae", url_apple_music: "https://music.apple.com/us/artist/lecrae/79aborada949", url_spotify: "https://open.spotify.com/artist/1Bi3NfVEub4Mx6ysdS0mSf", photo_url: null, status: "draft",
  },
  {
    name: "KB", type: "solo", founded_year: 2008, location: "St. Petersburg, Florida", church_label: "Reach Records",
    bio: "KB (Kevin Elijah Burgess) is a Christian rapper from St. Petersburg, Florida, signed to Lecrae's Reach Records. Known for his rapid-fire flow and theologically dense lyrics, KB brings academic rigor and street credibility to Christian hip-hop. His album 'Today We Rebel' showcased his ability to blend hard-hitting beats with deep theological content. KB represents the next generation of Christian rappers who refuse to compromise on either artistic quality or doctrinal substance.",
    style: "Christian hip-hop, rapid flow, theologically dense, hard-hitting production",
    awards: "Grammy nominations, Stellar Award nominations",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/KB_(rapper)",
    url_youtube: "https://www.youtube.com/@KB_HGA", url_apple_music: "https://music.apple.com/us/artist/kb/489261911", url_spotify: "https://open.spotify.com/artist/4AQhl6dZEdQKvYw3Sjf9wF", photo_url: null, status: "draft",
  },
  {
    name: "Crowder", type: "solo", founded_year: 2012, location: "Texarkana, Texas", church_label: null,
    bio: "David Crowder, performing as Crowder, is a worship leader and musician from Texarkana, Texas, known for genre-defying musical explorations. After disbanding the David Crowder*Band in 2012, he launched his solo career with a distinctive blend of folk, bluegrass, electronic, and worship music. His hit 'Good God Almighty' and albums like 'American Prodigal' showcase his refusal to be confined by genre boundaries. Crowder's iconic beard, creative visual presentations, and willingness to experiment have made him one of the most distinctive figures in Christian music.",
    style: "Genre-defying — folk, bluegrass, electronic, worship mashup, creative and quirky",
    awards: "Grammy nomination, GMA Dove Awards, Billboard chart success",
    url_website: "https://crowdermusic.com", url_wiki: "https://en.wikipedia.org/wiki/David_Crowder",
    url_youtube: "https://www.youtube.com/@CrowderMusic", url_apple_music: "https://music.apple.com/us/artist/crowder/646966701", url_spotify: "https://open.spotify.com/artist/43mWhBXSflkNHPHlAMvZnA", photo_url: null, status: "draft",
  },
  {
    name: "Sean Feucht", type: "solo", founded_year: 2020, location: "Redding, California", church_label: null,
    bio: "Sean Feucht is a worship leader, missionary, and activist who gained national attention with his 'Let Us Worship' outdoor worship gatherings that began during the COVID-19 pandemic in 2020. Holding worship events in public spaces, government buildings, and city streets, Feucht sparked both enthusiasm and controversy. His approach to worship as a form of public declaration and activism represents a distinct movement within contemporary Christianity. Songs from his live events have gained significant traction on digital platforms.",
    style: "Outdoor public worship, activist worship, spontaneous, culturally confrontational",
    awards: null,
    url_website: "https://seanfeucht.com", url_wiki: "https://en.wikipedia.org/wiki/Sean_Feucht",
    url_youtube: "https://www.youtube.com/@SeanFeucht", url_apple_music: "https://music.apple.com/us/artist/sean-feucht/371891507", url_spotify: "https://open.spotify.com/artist/4LeuqaGfT0j9TwMUTXw0sX", photo_url: null, status: "draft",
  },
  {
    name: "Leeland", type: "solo", founded_year: 2004, location: "Baytown, Texas", church_label: null,
    bio: "Leeland Mooring, performing as Leeland, is a worship leader from Baytown, Texas, who has been creating worship music since his teenage years. Initially leading a band of the same name, Leeland has evolved into a solo worship artist with a focus on spontaneous, Spirit-led worship. His songs 'Way Maker' (an English adaptation of Sinach's original), 'Lion and the Lamb,' and 'Inhabit' have become widely used in churches globally. Leeland's consistent dedication to worship ministry over two decades has earned him deep respect in the worship community.",
    style: "Spontaneous Spirit-led worship, passionate vocal delivery, prayer-room influenced",
    awards: "Grammy nominations, GMA Dove Awards",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/Leeland_(band)",
    url_youtube: "https://www.youtube.com/@LeelandOfficial", url_apple_music: "https://music.apple.com/us/artist/leeland/152762836", url_spotify: "https://open.spotify.com/artist/3fS1gkBfT4z2GHWgHMi9W6", photo_url: null, status: "draft",
  },
  {
    name: "Cody Carnes", type: "solo", founded_year: 2017, location: "Nashville, Tennessee", church_label: "Gateway Worship",
    bio: "Cody Carnes is a worship leader and songwriter married to Kari Jobe, based in Nashville, Tennessee. His songwriting has produced modern worship standards including 'Run to the Father,' 'Nothing Else,' and 'Christ Be Magnified.' Co-writing 'The Blessing' with Kari Jobe and Elevation Worship created one of the most significant worship songs of the decade. Carnes' music combines atmospheric production with passionate lyrical declarations, and his collaborative spirit has made him a sought-after co-writer across the worship industry.",
    style: "Atmospheric worship, passionate declarations, modern production, collaborative",
    awards: "GMA Dove Awards, Billboard chart success",
    url_website: "https://codycarnes.com", url_wiki: "https://en.wikipedia.org/wiki/Cody_Carnes",
    url_youtube: "https://www.youtube.com/@CodyCarnes", url_apple_music: "https://music.apple.com/us/artist/cody-carnes/1118974649", url_spotify: "https://open.spotify.com/artist/0oyBfx5kq6jv80wnMPrmBl", photo_url: null, status: "draft",
  },
  {
    name: "Brian & Jenn Johnson", type: "solo", founded_year: 2001, location: "Redding, California", church_label: "Bethel Music",
    bio: "Brian and Jenn Johnson are the founding worship leaders of Bethel Music and senior leaders at Bethel Church in Redding, California. Brian's songwriting has produced some of the most widely sung worship songs in the world, including 'No Longer Slaves' (co-written with Jonathan Helser) and 'Have It All.' Jenn is known for intimate, prophetic worship moments. Together, they have shaped the Bethel Music culture that emphasizes encounter, creativity, and spiritual freedom, influencing worship culture globally across denominations.",
    style: "Intimate prophetic worship, encounter-focused, creative freedom, Bethel culture",
    awards: "Multiple GMA Dove Award nominations, Billboard chart success",
    url_website: "https://bethelmusic.com", url_wiki: null,
    url_youtube: "https://www.youtube.com/@BrianAndJennJohnson", url_apple_music: "https://music.apple.com/us/artist/brian-jenn-johnson/390079972", url_spotify: "https://open.spotify.com/artist/5xkz8l0wNJpQhQNiOIYH5j", photo_url: null, status: "draft",
  },
  {
    name: "Kim Walker-Smith", type: "solo", founded_year: 2008, location: "Sacramento, California", church_label: "Jesus Culture",
    bio: "Kim Walker-Smith is the primary worship leader of Jesus Culture, known for her powerful, passionate vocal delivery and willingness to follow the Spirit into extended worship moments. Her voice has been described as one of the most recognizable in modern worship. Solo albums like 'Still Believe' and 'Wild Heart' showcase both her intimate worship side and her powerful prophetic declarations. Walker-Smith's fearless approach to worship leading has inspired a generation of female worship leaders to step boldly into their calling.",
    style: "Passionate prophetic worship, powerful female vocals, extended worship sets, bold",
    awards: "GMA Dove Award nominations",
    url_website: null, url_wiki: null,
    url_youtube: "https://www.youtube.com/@KimWalkerSmith", url_apple_music: "https://music.apple.com/us/artist/kim-walker-smith/299461648", url_spotify: "https://open.spotify.com/artist/6n3mVb4MDs9POtfCGG9bh9", photo_url: null, status: "draft",
  },
  {
    name: "Darlene Zschech", type: "solo", founded_year: 1986, location: "Sydney, Australia", church_label: "Hillsong Church",
    bio: "Darlene Zschech is a legendary Australian worship leader who served as the worship pastor of Hillsong Church from 1986 to 2007. She wrote 'Shout to the Lord,' one of the most well-known worship songs ever written, estimated to be sung by 25-30 million people weekly worldwide. Zschech's influence on modern worship music cannot be overstated — she helped establish Hillsong as a global worship brand and mentored countless worship leaders. Now leading Hope Unlimited Church on the Central Coast of Australia, she continues to write and record worship music.",
    style: "Classic contemporary worship, powerful female leadership, anthemic congregational songs",
    awards: "GMA Dove Awards, ARIA nominations, 'Shout to the Lord' — one of the most sung songs globally",
    url_website: "https://darlenezschech.com", url_wiki: "https://en.wikipedia.org/wiki/Darlene_Zschech",
    url_youtube: "https://www.youtube.com/@DarleneZschech", url_apple_music: "https://music.apple.com/us/artist/darlene-zschech/24685641", url_spotify: "https://open.spotify.com/artist/2D5Pzlqj2JuXdIJmhYkemz", photo_url: null, status: "draft",
  },
  {
    name: "Matt Redman", type: "solo", founded_year: 1993, location: "Brighton, England", church_label: null,
    bio: "Matt Redman is a British worship leader and songwriter who has been a leading voice in global worship since the 1990s. His song '10,000 Reasons (Bless the Lord)' won two Grammy Awards and has become one of the most-sung worship songs worldwide. Redman's songwriting is marked by theological depth and congregational accessibility. Other well-known songs include 'Blessed Be Your Name,' 'Heart of Worship,' and 'You Never Let Go.' He played a pivotal role in the UK worship movement alongside Tim Hughes and the Soul Survivor generation.",
    style: "British worship, theologically rich, congregationally accessible, hymn-like modern songs",
    awards: "2 Grammy Awards, multiple GMA Dove Awards, Worship Leader magazine honors",
    url_website: "https://mattredman.com", url_wiki: "https://en.wikipedia.org/wiki/Matt_Redman",
    url_youtube: "https://www.youtube.com/@MattRedmanVEVO", url_apple_music: "https://music.apple.com/us/artist/matt-redman/14242181", url_spotify: "https://open.spotify.com/artist/0DNvlhpOINSjaJYaP7Yqkm", photo_url: null, status: "draft",
  },
  {
    name: "Tim Hughes", type: "solo", founded_year: 1999, location: "Birmingham, England", church_label: null,
    bio: "Tim Hughes is a British worship leader and songwriter best known for writing 'Here I Am to Worship (Light of the World),' one of the most widely sung worship songs of the early 2000s. A key figure in the UK worship movement alongside Matt Redman, Hughes led worship at Soul Survivor festivals and Holy Trinity Brompton before planting a church in Birmingham. His songs combine simple, singable melodies with deep theological truth, making them accessible to congregations worldwide.",
    style: "British worship, simple melodies, theologically grounded, Soul Survivor generation",
    awards: "GMA Dove Awards, 'Here I Am to Worship' — one of the most-covered worship songs",
    url_website: null, url_wiki: "https://en.wikipedia.org/wiki/Tim_Hughes_(worship_leader)",
    url_youtube: null, url_apple_music: "https://music.apple.com/us/artist/tim-hughes/42824014", url_spotify: "https://open.spotify.com/artist/0gBYQlXOxWPCsIMp2FaXRV", photo_url: null, status: "draft",
  },
  {
    name: "Matt Maher", type: "solo", founded_year: 2006, location: "Nashville, Tennessee", church_label: null,
    bio: "Matt Maher is a Canadian-American worship leader and songwriter with a unique Catholic background that informs his worship expression. His songs 'Lord, I Need You,' 'Your Grace Is Enough,' and 'Because He Lives (Amen)' have been adopted across Catholic and Protestant churches alike, making him one of the rare artists who bridge these traditions. Maher's songwriting reflects deep liturgical and sacramental theology while remaining accessible to all Christian denominations. He has been a key collaborator with Chris Tomlin and other major worship artists.",
    style: "Catholic-rooted worship, ecumenical appeal, liturgically informed, acoustic-driven",
    awards: "Grammy nominations, GMA Dove Awards, CCLI top worship songs",
    url_website: "https://mattmahermusic.com", url_wiki: "https://en.wikipedia.org/wiki/Matt_Maher",
    url_youtube: "https://www.youtube.com/@MattMaher", url_apple_music: "https://music.apple.com/us/artist/matt-maher/72737564", url_spotify: "https://open.spotify.com/artist/6nVMyTqEe9iRBIjgFaLqiT", photo_url: null, status: "draft",
  },
  {
    name: "Natalie Grant", type: "solo", founded_year: 1999, location: "Nashville, Tennessee", church_label: null,
    bio: "Natalie Grant is a powerhouse Christian pop vocalist and eight-time GMA Dove Award Female Vocalist of the Year — more than any other artist in history. Her hits include 'Held,' 'In Better Hands,' and 'Face to Face.' Grant is also known for her humanitarian work as founder of Hope for Justice, an organization combating human trafficking. Her vocal ability rivals any mainstream pop artist, and her music addresses themes of faith through struggle, making her a beloved figure in contemporary Christian music.",
    style: "Christian pop, powerhouse vocals, emotionally driven, inspirational ballads",
    awards: "8x GMA Dove Award Female Vocalist of the Year, Grammy nominations",
    url_website: "https://nataliegrant.com", url_wiki: "https://en.wikipedia.org/wiki/Natalie_Grant",
    url_youtube: "https://www.youtube.com/@NatalieGrant", url_apple_music: "https://music.apple.com/us/artist/natalie-grant/15911520", url_spotify: "https://open.spotify.com/artist/60IRbhJkcEh3gE5VxG0o0h", photo_url: null, status: "draft",
  },
  {
    name: "Francesca Battistelli", type: "solo", founded_year: 2008, location: "New York City, New York", church_label: null,
    bio: "Francesca Battistelli is a Christian pop artist originally from New York City. Her debut single 'Free to Be Me' launched her career, and she won the GMA Dove Award for New Artist of the Year in 2008 and Artist of the Year in 2015. Her song 'Holy Spirit' became a modern worship classic, covered by numerous artists and used in churches worldwide. Battistelli's music blends mainstream pop sensibility with heartfelt faith expression, and her Italian-American energy brings a distinctive personality to Christian music.",
    style: "Christian pop, mainstream crossover potential, warm personality, radio-friendly",
    awards: "GMA Dove Award for Artist of the Year, Grammy nominations",
    url_website: "https://francescamusic.com", url_wiki: "https://en.wikipedia.org/wiki/Francesca_Battistelli",
    url_youtube: "https://www.youtube.com/@FrancescaBattistelli", url_apple_music: "https://music.apple.com/us/artist/francesca-battistelli/268558619", url_spotify: "https://open.spotify.com/artist/7fFMQ68DuVB5FP3Ij0mNJR", photo_url: null, status: "draft",
  },
  {
    name: "Danny Gokey", type: "solo", founded_year: 2010, location: "Nashville, Tennessee", church_label: null,
    bio: "Danny Gokey gained national attention as a contestant on American Idol Season 8 in 2009, where his story of losing his wife before the show resonated with millions. He transitioned from country to Christian music, finding his true calling. Hits like 'Tell Your Heart to Beat Again,' 'Haven't Seen It Yet,' and 'Stand in Faith' have made him one of the most successful artists in contemporary Christian music. Gokey's journey from tragedy to faith-fueled purpose infuses his music with genuine emotion and hope.",
    style: "Christian pop with country roots, inspirational, emotionally authentic, radio-friendly",
    awards: "GMA Dove Awards, K-LOVE Fan Awards, Billboard chart success",
    url_website: "https://dannygokey.com", url_wiki: "https://en.wikipedia.org/wiki/Danny_Gokey",
    url_youtube: "https://www.youtube.com/@DannyGokey", url_apple_music: "https://music.apple.com/us/artist/danny-gokey/338131412", url_spotify: "https://open.spotify.com/artist/2V7FHGhf6cN0es5oMjXtqf", photo_url: null, status: "draft",
  },
  {
    name: "Charity Gayle", type: "solo", founded_year: 2019, location: null, church_label: null,
    bio: "Charity Gayle is a worship leader and songwriter who burst onto the scene with powerful worship songs like 'Thank God I Do,' which became a viral sensation and crossed over to mainstream recognition. Her raw, anointed vocal delivery and simple yet profound songwriting have resonated with millions. 'I Am Loved' and 'Endless Praise' are among her other popular songs. Gayle represents the emerging wave of worship leaders who gain massive audiences through digital platforms and authentic ministry moments captured on video.",
    style: "Anointed worship, raw powerful vocals, simple profound songwriting, viral digital presence",
    awards: null,
    url_website: null, url_wiki: null,
    url_youtube: "https://www.youtube.com/@CharityGayle", url_apple_music: "https://music.apple.com/us/artist/charity-gayle/1089735938", url_spotify: "https://open.spotify.com/artist/2e0HXPN6V6x3GhsSIuX2aJ", photo_url: null, status: "draft",
  },
  {
    name: "Blessing Offor", type: "solo", founded_year: 2020, location: "Nashville, Tennessee", church_label: null,
    bio: "Blessing Offor is a Nigerian-American singer-songwriter from Nashville whose soulful voice and heartfelt storytelling have earned him critical acclaim and a Grammy nomination. Partially blind since childhood, Offor's music is deeply informed by his personal journey and Nigerian heritage. His song 'Brighter Days' and debut album 'My Tribe' blend folk, soul, and gospel influences into something uniquely personal. Offor represents the growing diversity of voices in contemporary Christian and inspirational music.",
    style: "Folk-soul-gospel fusion, deeply personal storytelling, Nigerian-American heritage",
    awards: "Grammy nomination, critical acclaim",
    url_website: "https://blessingoffor.com", url_wiki: "https://en.wikipedia.org/wiki/Blessing_Offor",
    url_youtube: "https://www.youtube.com/@BlessingOffor", url_apple_music: "https://music.apple.com/us/artist/blessing-offor/502088498", url_spotify: "https://open.spotify.com/artist/5Tov3oy5Jt6DB97YlUGHwC", photo_url: null, status: "draft",
  },
];

async function seed() {
  console.log(`Seeding ${artists.length} artists (v2 expansion)...`);
  let inserted = 0;

  for (const artist of artists) {
    const { data: existing } = await supabase
      .from("artists")
      .select("id")
      .eq("name", artist.name)
      .limit(1);

    if (existing && existing.length > 0) {
      console.log(`  Skipped (exists): ${artist.name}`);
      continue;
    }

    const { error } = await supabase.from("artists").insert(artist);
    if (error) {
      console.error(`  Error: ${artist.name}: ${error.message}`);
    } else {
      console.log(`  Inserted: ${artist.name}`);
      inserted++;
    }
  }

  // Auto-publish all new artists
  const { data: published } = await supabase
    .from("artists")
    .update({ status: "published" })
    .eq("status", "draft")
    .select("name");

  console.log(`\nPublished ${published?.length ?? 0} artists.`);
  console.log(`Done! Inserted ${inserted} new artists.`);
}

seed();
