import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

type ArtistSeed = {
  name: string;
  type: "band" | "solo";
  founded_year: number | null;
  location: string | null;
  church_label: string | null;
  bio: string;
  style: string;
  awards: string | null;
  url_website: string | null;
  url_wiki: string | null;
  url_youtube: string | null;
  url_apple_music: string | null;
  url_spotify: string | null;
  photo_url: string | null;
  status: "draft";
};

const artists: ArtistSeed[] = [
  // === BANDS ===
  {
    name: "Bethel Music",
    type: "band",
    founded_year: 2001,
    location: "Redding, California",
    church_label: "Bethel Church",
    bio: "Bethel Music is a worship ministry born out of Bethel Church in Redding, California. Founded in 2001, the collective has grown into one of the most influential forces in contemporary worship music. Their roster includes worship leaders like Brian and Jenn Johnson, Josh Baldwin, and Kristene DiMarco. Known for creating atmospheric, Spirit-led worship experiences, Bethel Music blends intimate devotional moments with powerful anthems. Albums like 'Without Words' and 'Victory' have become staples in churches worldwide. They also host the annual Heaven Come Conference and operate a School of Worship.",
    style: "Atmospheric worship, prophetic spontaneous worship, modern hymns with ambient production",
    awards: "Multiple GMA Dove Award nominations, Billboard chart entries",
    url_website: "https://bethelmusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Bethel_Music",
    url_youtube: "https://www.youtube.com/@BethelMusic",
    url_apple_music: "https://music.apple.com/us/artist/bethel-music/300518869",
    url_spotify: "https://open.spotify.com/artist/6BnR7TJBknI0MRnEb6eEMp",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Elevation Worship",
    type: "band",
    founded_year: 2007,
    location: "Charlotte, North Carolina",
    church_label: "Elevation Church",
    bio: "Elevation Worship is the worship ministry of Elevation Church, led by Pastor Steven Furtick in Charlotte, North Carolina. Since 2007, they have released numerous albums that consistently top Christian music charts. Their song 'O Come to the Altar' became one of the most-sung worship songs globally. The team includes worship leaders Chris Brown, Jonsal Barrientes, and Tiffany Hudson. Known for blending pop production quality with genuine worship expression, Elevation Worship has amassed billions of streams. Their collaborations with Maverick City Music produced the critically acclaimed 'Old Church Basement' album.",
    style: "Pop-influenced worship, anthemic choruses, polished modern production",
    awards: "GMA Dove Awards, RIAA certified songs, Billboard #1 albums",
    url_website: "https://elevationworship.com",
    url_wiki: "https://en.wikipedia.org/wiki/Elevation_Worship",
    url_youtube: "https://www.youtube.com/@elevationworship",
    url_apple_music: "https://music.apple.com/us/artist/elevation-worship/295815328",
    url_spotify: "https://open.spotify.com/artist/5BROReidLFPGlTNWkqm3E5",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Hillsong Worship",
    type: "band",
    founded_year: 1983,
    location: "Sydney, Australia",
    church_label: "Hillsong Church",
    bio: "Hillsong Worship, originating from Hillsong Church in Sydney, Australia, is one of the most recognized worship brands in the world. Since the early 1980s, they have produced timeless hymns sung in churches across every continent. Songs like 'Shout to the Lord,' 'Oceans (Where Feet May Fail),' and 'What a Beautiful Name' have defined modern worship music. The collective has included worship leaders such as Darlene Zschech, Brooke Ligertwood, and Ben Fielding. Their annual conferences and live recordings have set the standard for contemporary worship events.",
    style: "Arena worship, modern hymns, dynamic builds with congregational singability",
    awards: "Grammy Award for Best Contemporary Christian Music Album, multiple GMA Dove Awards",
    url_website: "https://hillsong.com/worship",
    url_wiki: "https://en.wikipedia.org/wiki/Hillsong_Worship",
    url_youtube: "https://www.youtube.com/@hillsongworship",
    url_apple_music: "https://music.apple.com/us/artist/hillsong-worship/5765526",
    url_spotify: "https://open.spotify.com/artist/3G4sQCGjXXimedLPi7vJhm",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jesus Culture",
    type: "band",
    founded_year: 1999,
    location: "Sacramento, California",
    church_label: "Jesus Culture Church",
    bio: "Jesus Culture began as a youth ministry movement at Bethel Church in Redding, California in 1999 before establishing their own church in Sacramento. Led by worship leaders Kim Walker-Smith and Chris Quilala, the ministry became known for passionate, revival-oriented worship. Their live recordings capture raw, extended worship moments that emphasize encounter over performance. Songs like 'Your Love Never Fails' and 'Fierce' have become worship standards. Jesus Culture conferences have drawn tens of thousands of young worshippers, making them a catalyst for the modern worship movement.",
    style: "Revival worship, passionate extended worship sets, rock-influenced praise",
    awards: "GMA Dove Award nominations, Billboard chart success",
    url_website: "https://jesusculture.com",
    url_wiki: "https://en.wikipedia.org/wiki/Jesus_Culture",
    url_youtube: "https://www.youtube.com/@JesusCultureMusic",
    url_apple_music: "https://music.apple.com/us/artist/jesus-culture/259909540",
    url_spotify: "https://open.spotify.com/artist/0PfOZOVEbGGJccQPMfXmhi",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Casting Crowns",
    type: "band",
    founded_year: 1999,
    location: "Daytona Beach, Florida",
    church_label: null,
    bio: "Casting Crowns is a contemporary Christian band formed in 1999, led by youth pastor and vocalist Mark Hall. Based originally in Daytona Beach, Florida, the band has become one of the best-selling acts in Christian music history. Their lyrics focus on real-life struggles and faith challenges, resonating deeply with church communities. Hits like 'Who Am I,' 'Praise You in This Storm,' and 'Just Be Held' have earned them widespread acclaim. With over 12 million albums sold, they hold the record for the most consecutive No. 1 debuts on the Billboard Christian Albums chart.",
    style: "Contemporary Christian pop-rock, lyric-driven storytelling, congregational anthems",
    awards: "Grammy Award, 23 GMA Dove Awards, American Music Award, Billboard Music Awards",
    url_website: "https://castingcrowns.com",
    url_wiki: "https://en.wikipedia.org/wiki/Casting_Crowns",
    url_youtube: "https://www.youtube.com/@CastingCrowns",
    url_apple_music: "https://music.apple.com/us/artist/casting-crowns/65237594",
    url_spotify: "https://open.spotify.com/artist/1DvB1HYqmOyfr6bMFblwqQ",
    photo_url: null,
    status: "draft",
  },
  {
    name: "MercyMe",
    type: "band",
    founded_year: 1994,
    location: "Greenville, Texas",
    church_label: null,
    bio: "MercyMe is a contemporary Christian band formed in 1994 in Greenville, Texas, led by vocalist Bart Millard. They achieved mainstream crossover success with 'I Can Only Imagine,' which became the best-selling Christian single of all time and inspired a major motion picture in 2018. The band's sound bridges Christian pop and worship, making their music accessible to both church and mainstream audiences. Albums like 'Almost There' and 'Inhale (Exhale)' showcase their ability to craft radio-friendly songs with deep spiritual content. MercyMe has sold over 10 million albums.",
    style: "Christian pop-rock, radio-friendly worship, inspirational ballads",
    awards: "8 GMA Dove Awards, multiple Grammy nominations, American Music Awards",
    url_website: "https://mercyme.org",
    url_wiki: "https://en.wikipedia.org/wiki/MercyMe",
    url_youtube: "https://www.youtube.com/@MercyMe",
    url_apple_music: "https://music.apple.com/us/artist/mercyme/20668390",
    url_spotify: "https://open.spotify.com/artist/4KETRdqMJujwBkYU85k5nt",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Housefires",
    type: "band",
    founded_year: 2014,
    location: "Atlanta, Georgia",
    church_label: null,
    bio: "Housefires is a worship collective based in Atlanta, Georgia, formed in 2014 by worship leader and songwriter Pat Barrett. The group emphasizes organic, house-church-style worship with raw, unpolished recordings that capture genuine community moments. Their song 'Good Good Father' (co-written by Barrett and Tony Brown) became a global worship anthem, covered by Chris Tomlin and topping charts worldwide. Housefires intentionally keeps their sound intimate and accessible, reflecting their belief that the best worship happens in small, authentic gatherings rather than large productions.",
    style: "Organic acoustic worship, intimate house-church feel, singable melodies",
    awards: "GMA Dove Award for Worship Song of the Year ('Good Good Father')",
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@Housefires",
    url_apple_music: "https://music.apple.com/us/artist/housefires/908498188",
    url_spotify: "https://open.spotify.com/artist/5vlqSCOzMJcUYoJzzE8xzQ",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Maverick City Music",
    type: "band",
    founded_year: 2018,
    location: "Atlanta, Georgia",
    church_label: "Maverick City",
    bio: "Maverick City Music emerged in 2018 from Atlanta, Georgia, with a mission to champion diversity and break down barriers in the worship music industry. Founded by Tony Brown and Jonathan Jay, the collective brings together songwriters from varied backgrounds who might otherwise be overlooked by mainstream Christian music. Their approach — recording songs written by emerging artists in collaborative sessions — has produced a distinctive, genre-blending sound. The group exploded in popularity with albums like 'Jubilee' and their collaboration with Elevation Worship on 'Old Church Basement.' They won the Grammy for Best Contemporary Christian Music Album in 2022.",
    style: "Genre-blending worship (gospel, R&B, folk, pop), diverse collaborative sound, spontaneous worship",
    awards: "Grammy Award for Best Contemporary Christian Music Album (2022, 2023), multiple GMA Dove Awards",
    url_website: "https://maverickcitymusic.com",
    url_wiki: "https://en.wikipedia.org/wiki/Maverick_City_Music",
    url_youtube: "https://www.youtube.com/@MaverickCityMusic",
    url_apple_music: "https://music.apple.com/us/artist/maverick-city-music/1441972522",
    url_spotify: "https://open.spotify.com/artist/3Mz1bR0vCPN6vMLMFaIWFN",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Selah",
    type: "band",
    founded_year: 1997,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "Selah is a Christian vocal trio formed in 1997 in Nashville, Tennessee. The group, featuring Todd Smith, Allan Hall, and Amy Perry, is renowned for their rich vocal harmonies and powerful arrangements of hymns and worship songs. Their rendition of 'You Raise Me Up' introduced the song to American audiences before Josh Groban's mainstream version. With over 4 million albums sold, Selah has carved a unique niche blending classical vocal technique with contemporary worship and hymn arrangements. They are particularly beloved for breathing new life into traditional hymns.",
    style: "Vocal harmony-driven worship, hymn arrangements, classical-contemporary blend",
    awards: "11 GMA Dove Awards including Group of the Year",
    url_website: "https://selahonline.com",
    url_wiki: "https://en.wikipedia.org/wiki/Selah_(band)",
    url_youtube: "https://www.youtube.com/@selahmusic",
    url_apple_music: "https://music.apple.com/us/artist/selah/3504209",
    url_spotify: "https://open.spotify.com/artist/1jHbgGFfKndQ1FQfGOjIAL",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Kutless",
    type: "band",
    founded_year: 2000,
    location: "Portland, Oregon",
    church_label: null,
    bio: "Kutless is a Christian rock band formed in 2000 in Portland, Oregon, led by vocalist Jon Micah Sumrall. Initially known for their hard-rock sound, the band transitioned toward worship music with albums like 'It Is Well' and 'Surrender.' This evolution reflected Sumrall's growing passion for leading congregational worship. Their song 'Strong Tower' became a signature hit. Kutless has sold over 2.5 million albums, successfully bridging the gap between Christian rock and worship music markets while maintaining a loyal fanbase across both genres.",
    style: "Christian rock transitioning to worship rock, powerful vocals, guitar-driven anthems",
    awards: "GMA Dove Award nominations, Billboard chart entries",
    url_website: "https://kutless.com",
    url_wiki: "https://en.wikipedia.org/wiki/Kutless",
    url_youtube: "https://www.youtube.com/@Kutless",
    url_apple_music: "https://music.apple.com/us/artist/kutless/15584992",
    url_spotify: "https://open.spotify.com/artist/3pFdqGJPsYmxMrOdN8rSzn",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Red Rocks Worship",
    type: "band",
    founded_year: 2014,
    location: "Golden, Colorado",
    church_label: "Red Rocks Church",
    bio: "Red Rocks Worship is the worship ministry of Red Rocks Church based in Golden, Colorado. Formed in 2014, the group has quickly gained national recognition for their energetic yet deeply reverent worship style. Their breakthrough single 'Rescue' gained significant traction on Christian radio and streaming platforms. The team, led by worship pastors including Jonny Diaz and Jake Espy, creates music that blends modern pop sensibilities with genuine worship moments. Red Rocks Worship represents a new generation of church-based worship teams reaching audiences far beyond their local congregation.",
    style: "Modern pop worship, energetic live performance, radio-friendly production",
    awards: null,
    url_website: "https://redrocksworship.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@RedRocksWorship",
    url_apple_music: "https://music.apple.com/us/artist/red-rocks-worship/966498498",
    url_spotify: "https://open.spotify.com/artist/6lHJvBn47PVhMTXijg4Xv4",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Caleb & Kelsey",
    type: "band",
    founded_year: 2015,
    location: null,
    church_label: null,
    bio: "Caleb and Kelsey Grimm are a husband-and-wife duo who gained massive popularity through their YouTube worship covers starting around 2015. Known for their stunning vocal harmonies and creative medley arrangements, they have amassed hundreds of millions of views online. Their covers of popular worship songs and hymns, often arranged as medleys, showcase exceptional vocal chemistry and musical creativity. While primarily known as cover artists, Caleb & Kelsey have released original worship music and continue to reach a vast digital audience with their accessible, harmony-rich approach to familiar worship songs.",
    style: "Vocal harmony covers, creative worship medleys, YouTube-native acoustic arrangements",
    awards: null,
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@CalebandKelsey",
    url_apple_music: "https://music.apple.com/us/artist/caleb-kelsey/1089498281",
    url_spotify: "https://open.spotify.com/artist/74XgjYglMNRpSOBklIVPVE",
    photo_url: null,
    status: "draft",
  },

  // === SOLO ARTISTS ===
  {
    name: "Phil Wickham",
    type: "solo",
    founded_year: 2003,
    location: "San Diego, California",
    church_label: null,
    bio: "Phil Wickham is a worship leader and songwriter from San Diego, California, who has been releasing music since 2003. He is widely regarded as one of the premier worship songwriters of his generation. His song 'This Is Amazing Grace' won the GMA Dove Award for Worship Song of the Year, and subsequent hits like 'Battle Belongs,' 'House of the Lord,' and 'Hymn of Heaven' have become church staples worldwide. Wickham's distinctive tenor voice and gift for writing singable melodies have made him one of the most-streamed Christian artists. He leads worship at various churches and conferences while maintaining a prolific recording career.",
    style: "Modern worship anthems, soaring melodies, electronic-acoustic blend",
    awards: "GMA Dove Award for Worship Song of the Year, multiple Billboard #1 songs",
    url_website: "https://philwickham.com",
    url_wiki: "https://en.wikipedia.org/wiki/Phil_Wickham",
    url_youtube: "https://www.youtube.com/@PhilWickham",
    url_apple_music: "https://music.apple.com/us/artist/phil-wickham/79aborada8581",
    url_spotify: "https://open.spotify.com/artist/5FcJRFsJoTXGq5oaMBiOkj",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jeremy Riddle",
    type: "solo",
    founded_year: 2004,
    location: "Anaheim, California",
    church_label: "Bethel Music",
    bio: "Jeremy Riddle is a worship leader and songwriter who has been a key voice in the Bethel Music collective. Originally from Southern California, Riddle is known for his raw, passionate approach to worship leading and his gift for spontaneous prophetic worship. His songs 'Furious' and 'Fall Afresh' have been widely adopted in churches. After years with Bethel Music, Riddle continued to lead worship and write songs that emphasize intimate encounter with God. His worship style is marked by vulnerability and a willingness to follow the Spirit in unscripted moments.",
    style: "Prophetic spontaneous worship, intimate acoustic worship, raw passionate vocals",
    awards: null,
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@JeremyRiddleMusic",
    url_apple_music: "https://music.apple.com/us/artist/jeremy-riddle/64729032",
    url_spotify: "https://open.spotify.com/artist/5B2hnVaKGPRHMsKGJi7E8X",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Amanda Cook",
    type: "solo",
    founded_year: 2015,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Amanda Cook is a Canadian-born worship artist and songwriter who has been part of the Bethel Music collective. Her introspective songwriting sets her apart in the worship space, exploring themes of identity, doubt, and divine mystery with poetic depth. Her debut album 'Brave New World' marked a departure from typical worship conventions, blending folk and indie influences with worship lyrics. Songs like 'You Make Me Brave' (co-written with worship pastor Bobby Strand) became a global anthem. Cook's artistry brings a contemplative, literary quality to contemporary worship music.",
    style: "Indie-folk worship, introspective and poetic lyrics, contemplative atmospheres",
    awards: null,
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@AmandaCookMusic",
    url_apple_music: "https://music.apple.com/us/artist/amanda-cook/1051597498",
    url_spotify: "https://open.spotify.com/artist/2UZMlIwnCSjDYz2U5bpLcB",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Steffany Gretzinger",
    type: "solo",
    founded_year: 2014,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Steffany Gretzinger is a worship leader and songwriter known for her ethereal vocal quality and deeply intimate worship style. A key member of the Bethel Music collective, she has contributed iconic songs like 'No One Ever Cared for Me Like Jesus' and 'Forever Amen.' Her album 'The Narrow Road' showcased her ability to blend folk, Americana, and worship into something entirely unique. Gretzinger is recognized for creating worship spaces that feel like sacred encounters rather than performances. Her voice, often described as haunting and angelic, has made her one of the most distinctive artists in modern worship.",
    style: "Ethereal folk-worship, intimate vocal delivery, Americana-influenced worship",
    awards: null,
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@SteffanyGretzinger",
    url_apple_music: "https://music.apple.com/us/artist/steffany-gretzinger/885806498",
    url_spotify: "https://open.spotify.com/artist/4MhpXzNPEav5CRS9aQvXnR",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Josh Baldwin",
    type: "solo",
    founded_year: 2014,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Josh Baldwin is a worship leader and songwriter from the Bethel Music collective based in Redding, California. His warm, accessible vocal style and gift for crafting singable melodies have produced several widely adopted worship songs. 'Stand in Your Love,' his breakthrough hit, topped Christian radio charts and became a congregational favorite. Baldwin's music combines folk-pop warmth with worship authenticity, creating songs that feel both personal and communal. His albums 'The War Is Over' and 'Evidence' further established him as a reliable voice in contemporary worship songwriting.",
    style: "Folk-pop worship, warm accessible vocals, radio-friendly worship anthems",
    awards: "Billboard #1 Christian Airplay with 'Stand in Your Love'",
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@JoshBaldwinMusic",
    url_apple_music: "https://music.apple.com/us/artist/josh-baldwin/327073054",
    url_spotify: "https://open.spotify.com/artist/4aTjiLLH6x0DOhd8QHXQ9d",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Lauren Daigle",
    type: "solo",
    founded_year: 2013,
    location: "Lafayette, Louisiana",
    church_label: null,
    bio: "Lauren Daigle is a Grammy Award-winning singer-songwriter from Lafayette, Louisiana, who has achieved remarkable crossover success between Christian and mainstream pop markets. Her 2018 album 'Look Up Child' debuted at No. 3 on the Billboard 200 — the highest-charting Christian album in over a decade. The single 'You Say' spent a record-breaking 100+ weeks atop the Hot Christian Songs chart and crossed over to mainstream radio. Daigle's rich, soulful voice draws comparisons to Adele, and her music bridges the gap between worship, pop, and soul with rare authenticity. She has sold millions of albums worldwide.",
    style: "Pop-soul crossover, rich soulful vocals, mainstream-accessible Christian music",
    awards: "2 Grammy Awards, 7 GMA Dove Awards, Billboard Music Awards, American Music Award",
    url_website: "https://laurendaigle.com",
    url_wiki: "https://en.wikipedia.org/wiki/Lauren_Daigle",
    url_youtube: "https://www.youtube.com/@LaurenDaigle",
    url_apple_music: "https://music.apple.com/us/artist/lauren-daigle/890853803",
    url_spotify: "https://open.spotify.com/artist/4sD89EVYlvcMzHffGrbC3S",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jonathan David & Melissa Helser",
    type: "solo",
    founded_year: 2003,
    location: "Sophia, North Carolina",
    church_label: "Bethel Music",
    bio: "Jonathan David and Melissa Helser are a husband-and-wife worship duo from Sophia, North Carolina, closely connected to the Bethel Music family. They run a discipleship community called 'A Place for the Heart' on their farm. Their worship is deeply personal and often emerges from extended times of prayer and community life. The Helsers wrote 'No Longer Slaves,' one of the most impactful worship songs of the 2010s, which has been covered and sung in churches worldwide. Their music carries a raw, prophetic quality that reflects their emphasis on identity and freedom in Christ.",
    style: "Prophetic folk worship, raw community-born songs, intimate farm-house recordings",
    awards: "GMA Dove Award nomination for 'No Longer Slaves'",
    url_website: "https://jonathanhelser.com",
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@JonathanDavidMelissaHelser",
    url_apple_music: "https://music.apple.com/us/artist/jonathan-david-melissa-helser/306529981",
    url_spotify: "https://open.spotify.com/artist/0P6JxPMVUfPDVYYkpioH5r",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Kristene DiMarco",
    type: "solo",
    founded_year: 2011,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Kristene DiMarco is a worship leader and songwriter within the Bethel Music collective. Her songwriting is marked by theological depth and emotional honesty, exploring themes of surrender, trust, and the faithfulness of God. Her song 'It Is Well' (a reimagined version of the classic hymn) became a signature piece, and 'Take Courage' resonated deeply with listeners facing difficult seasons. DiMarco's vocal style is warm and inviting, creating space for congregational participation. Her albums blend modern worship production with timeless lyrical themes.",
    style: "Theologically rich worship, modern hymn writing, warm inviting vocals",
    awards: null,
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@KristeneDiMarco",
    url_apple_music: "https://music.apple.com/us/artist/kristene-dimarco/468937063",
    url_spotify: "https://open.spotify.com/artist/2yYkiPZxDsGoSJpSaFQpts",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Cory Asbury",
    type: "solo",
    founded_year: 2009,
    location: "Redding, California",
    church_label: "Bethel Music",
    bio: "Cory Asbury is a worship leader and songwriter best known for the global hit 'Reckless Love,' which won the GMA Dove Award for Song of the Year in 2018 and Worship Song of the Year in 2019. A member of the Bethel Music collective, Asbury's songwriting is characterized by bold declarations of God's relentless pursuit and unconditional love. 'Reckless Love' topped multiple charts and was one of the most-streamed worship songs of the decade. His follow-up work, including the album 'To Love a Fool,' continued to push creative boundaries while maintaining worship accessibility.",
    style: "Anthemic worship, bold lyrical declarations, pop-worship crossover",
    awards: "GMA Dove Award for Song of the Year and Worship Song of the Year",
    url_website: null,
    url_wiki: "https://en.wikipedia.org/wiki/Cory_Asbury",
    url_youtube: "https://www.youtube.com/@CoryAsbury",
    url_apple_music: "https://music.apple.com/us/artist/cory-asbury/316498583",
    url_spotify: "https://open.spotify.com/artist/2MqXGPlBFPqZsN0vE5vLs7",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Brandon Lake",
    type: "solo",
    founded_year: 2019,
    location: "Charleston, South Carolina",
    church_label: "Maverick City Music / Bethel Music",
    bio: "Brandon Lake is a worship leader and songwriter from Charleston, South Carolina, who has become one of the most prolific voices in modern worship. A core member of both Maverick City Music and a contributor to Bethel Music, Lake's songs are sung in churches worldwide. His hits include 'Gratitude,' 'Yet,' and 'Count 'Em.' Lake's energetic worship leading style and gift for melody have earned him Grammy Awards and widespread recognition. His solo album 'Coat of Many Colors' debuted at No. 1 on multiple charts. Lake represents the new generation of worship leaders who move fluidly between collectives and denominations.",
    style: "High-energy worship, gospel-influenced, melodic anthems with spontaneous moments",
    awards: "Grammy Awards, GMA Dove Awards, Billboard #1 albums",
    url_website: null,
    url_wiki: "https://en.wikipedia.org/wiki/Brandon_Lake",
    url_youtube: "https://www.youtube.com/@BrandonLakeMusic",
    url_apple_music: "https://music.apple.com/us/artist/brandon-lake/1086498098",
    url_spotify: "https://open.spotify.com/artist/0ycfJBU26OhS0QSzHHaaxs",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Pat Barrett",
    type: "solo",
    founded_year: 2018,
    location: "Atlanta, Georgia",
    church_label: "Housefires",
    bio: "Pat Barrett is a worship leader and songwriter based in Atlanta, Georgia, known as the founder of the Housefires worship collective. He co-wrote 'Good Good Father' with Tony Brown, which became one of the most impactful worship songs of the 2010s — later recorded by Chris Tomlin and winning the GMA Dove Award for Song of the Year. Barrett's solo work, including the album 'Pat Barrett,' reflects his heart for simple, singable worship. His song 'Build My Life' (co-written with multiple writers) has also become a modern worship standard sung globally.",
    style: "Simple acoustic worship, singable melodies, organic folk-influenced praise",
    awards: "GMA Dove Award for Song of the Year ('Good Good Father' via Chris Tomlin's version)",
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@PatBarrettMusic",
    url_apple_music: "https://music.apple.com/us/artist/pat-barrett/1365711998",
    url_spotify: "https://open.spotify.com/artist/6rI75wRLcUiYEaEA1kKors",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Ellie Holcomb",
    type: "solo",
    founded_year: 2013,
    location: "Nashville, Tennessee",
    church_label: null,
    bio: "Ellie Holcomb is a singer-songwriter from Nashville, Tennessee, who combines folk-pop sensibility with deeply personal worship lyrics. Before her solo career, she toured as part of her husband's band, Drew Holcomb and the Neighbors. Her debut solo album 'As Sure as the Sun' won the GMA Dove Award for New Artist of the Year in 2014. Holcomb is also a bestselling children's book author, with titles like 'Who Sang the First Song?' Her music is marked by gentle sincerity, acoustic warmth, and lyrics that find the sacred in everyday moments.",
    style: "Folk-pop worship, gentle acoustic arrangements, heartfelt singer-songwriter",
    awards: "GMA Dove Award for New Artist of the Year",
    url_website: "https://ellieholcomb.com",
    url_wiki: "https://en.wikipedia.org/wiki/Ellie_Holcomb",
    url_youtube: "https://www.youtube.com/@EllieHolcomb",
    url_apple_music: "https://music.apple.com/us/artist/ellie-holcomb/332aborada729",
    url_spotify: "https://open.spotify.com/artist/1YLJGHnrBhKJxFPHOi4B5Y",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Chris Tomlin",
    type: "solo",
    founded_year: 1995,
    location: "Grand Saline, Texas",
    church_label: null,
    bio: "Chris Tomlin is arguably the most influential worship songwriter of the 21st century. Based originally from Grand Saline, Texas, Tomlin has been writing and leading worship since the mid-1990s. TIME Magazine called him the 'most often sung artist anywhere.' Songs like 'How Great Is Our God,' 'Amazing Grace (My Chains Are Gone),' 'Good Good Father,' and 'Holy Forever' are sung by an estimated 20-30 million people weekly. With over 18 studio albums, multiple Grammy nominations, and 30+ GMA Dove Awards, Tomlin has shaped the sound and vocabulary of modern congregational worship globally.",
    style: "Congregational worship anthems, accessible melodies, modern hymn writing",
    awards: "Grammy Award, 30+ GMA Dove Awards, BMI Songwriter of the Year (multiple times)",
    url_website: "https://christomlin.com",
    url_wiki: "https://en.wikipedia.org/wiki/Chris_Tomlin",
    url_youtube: "https://www.youtube.com/@ChrisTomlin",
    url_apple_music: "https://music.apple.com/us/artist/chris-tomlin/5765662",
    url_spotify: "https://open.spotify.com/artist/6SJhNECpRMaftpOxMG6RqP",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Naomi Raine",
    type: "solo",
    founded_year: 2020,
    location: "Atlanta, Georgia",
    church_label: "Maverick City Music",
    bio: "Naomi Raine is a worship leader and songwriter who rose to prominence as a core member of Maverick City Music. With roots in gospel and classical training, Raine brings a powerhouse vocal ability and deep musical sophistication to modern worship. Her contributions to Maverick City's collaborative recordings have been pivotal to the group's Grammy-winning sound. Songs like 'Promises' and 'Jireh' (featuring Chandler Moore and Naomi Raine) have become worship anthems. Raine represents the diversity and musical excellence that defines the Maverick City movement, blending gospel tradition with contemporary worship innovation.",
    style: "Gospel-influenced worship, powerful vocal runs, musically sophisticated arrangements",
    awards: "Grammy Award (with Maverick City Music), GMA Dove Awards",
    url_website: null,
    url_wiki: null,
    url_youtube: "https://www.youtube.com/@NaomiRaine",
    url_apple_music: "https://music.apple.com/us/artist/naomi-raine/1492497863",
    url_spotify: "https://open.spotify.com/artist/6e2b6MK5dJcTB8dvPOSxf2",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Jordan Smith",
    type: "solo",
    founded_year: 2015,
    location: "Harlan, Kentucky",
    church_label: null,
    bio: "Jordan Smith is a singer from Harlan, Kentucky, who gained national fame as the winner of Season 9 of NBC's 'The Voice' in 2015, mentored by Adam Levine. His powerful tenor voice and emotional delivery captivated millions. Following his victory, Smith pursued a career in Christian and inspirational music, releasing albums that showcase his vocal range and faith-centered lyrics. His rendition of 'Mary Did You Know' and original songs like 'Stand in the Light' resonated with Christian audiences. Smith's journey from small-town Kentucky to national prominence mirrors the inspirational themes in his music.",
    style: "Powerful vocal performances, inspirational Christian pop, classical-influenced",
    awards: "Winner of The Voice Season 9",
    url_website: null,
    url_wiki: "https://en.wikipedia.org/wiki/Jordan_Smith_(singer)",
    url_youtube: "https://www.youtube.com/@JordanSmithMusic",
    url_apple_music: "https://music.apple.com/us/artist/jordan-smith/1059043730",
    url_spotify: "https://open.spotify.com/artist/0VyTDJ2ZPqJcuY1xjCh7Zy",
    photo_url: null,
    status: "draft",
  },
  {
    name: "CeCe Winans",
    type: "solo",
    founded_year: 1984,
    location: "Detroit, Michigan",
    church_label: null,
    bio: "CeCe Winans is a gospel music legend and one of the best-selling female gospel artists of all time. Born into the renowned Winans musical family of Detroit, Michigan, she first gained fame as half of the duo BeBe & CeCe Winans in the 1980s. Her solo career has produced iconic albums and songs that span traditional gospel, contemporary Christian, and R&B. With over 17 million albums sold, 15 Grammy Awards, and 28 GMA Dove Awards, Winans is a towering figure in gospel music history. She continues to record and lead worship, bridging generations of gospel music.",
    style: "Traditional and contemporary gospel, R&B-influenced worship, powerful vocal ministry",
    awards: "15 Grammy Awards, 28 GMA Dove Awards, 7 Stellar Awards",
    url_website: "https://cecewinans.com",
    url_wiki: "https://en.wikipedia.org/wiki/CeCe_Winans",
    url_youtube: "https://www.youtube.com/@CeCeWinans",
    url_apple_music: "https://music.apple.com/us/artist/cece-winans/95498",
    url_spotify: "https://open.spotify.com/artist/5jFJC3geFByYB7RVIqfIbR",
    photo_url: null,
    status: "draft",
  },
  {
    name: "Kari Jobe",
    type: "solo",
    founded_year: 2004,
    location: "Waco, Texas",
    church_label: "Gateway Church",
    bio: "Kari Jobe is a worship leader and songwriter from Waco, Texas, who has been a leading voice in contemporary worship since the early 2000s. She served as a worship leader at Gateway Church in Dallas and has released multiple acclaimed albums. Her songs 'Revelation Song,' 'Forever (We Sing Hallelujah),' and 'The Blessing' (co-written with her husband Cody Carnes and Elevation Worship) are modern worship classics. 'The Blessing,' released during the COVID-19 pandemic, became a global phenomenon with churches worldwide creating their own versions. Jobe's voice is both powerful and tender, suited for intimate worship and large-scale gatherings alike.",
    style: "Cinematic worship, powerful yet tender vocals, anthemic worship ballads",
    awards: "2 Grammy nominations, GMA Dove Awards, Billboard chart entries",
    url_website: "https://karijobe.com",
    url_wiki: "https://en.wikipedia.org/wiki/Kari_Jobe",
    url_youtube: "https://www.youtube.com/@KariJobe",
    url_apple_music: "https://music.apple.com/us/artist/kari-jobe/82994746",
    url_spotify: "https://open.spotify.com/artist/41KaEPMYRvFShJGmGvS5CW",
    photo_url: null,
    status: "draft",
  },
];

async function seed() {
  console.log(`Seeding ${artists.length} artists...`);

  for (const artist of artists) {
    // Check if artist already exists
    const { data: existing } = await supabase
      .from("artists")
      .select("id")
      .eq("name", artist.name)
      .limit(1);

    if (existing && existing.length > 0) {
      console.log(`  Skipped (exists): ${artist.name}`);
      continue;
    }

    const { error } = await supabase.from("artists").insert(artist);

    if (error) {
      console.error(`  Error inserting ${artist.name}:`, error.message);
    } else {
      console.log(`  Inserted: ${artist.name}`);
    }
  }

  console.log("Done!");
}

seed();
